### ISSUE TITLE
A way to pause a server

### ISSUE THREAD

**Issue by LogischJo** [ControlPanel-gg/dashboard#104]
# 🚀 Feature Request

### Is your proposal related to a problem?

An way to stop an server if your friends are not playing on them currently (enable / disable in config)

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

I would like an button which works like the delete button, but keep the server and names it paused + suspend them in the panel.

**Comment by RamonRobben** [comment]
@LogischJo If you have ideas on how to implement this feel free to discuss here.
I am not comfortable with giving the user the ability to suspend / unsuspend their server whenever they want as this can possibly bypass the current automatic suspend / unsuspend.

I'd assume you also want to keep the server files while the server is in this "paused" state.

**Comment by anondev-sudo** [comment]
When user pauses server, you can toggle install mode so users will not be able to access the server and it will be not suspended.


There should be option that admins can set monthly fee for paused servers  in config (as you are storing the server data). When server is paused, remove hourly part of paused server fee from user balance. When running out of credits, suspend server

**Comment by DWAA1660** [comment]
a workaround for this is just making a cancelled plan or whatever that has barely any resources that users can downgrade too so im not sure if this has alot of use. just a thought

**Comment by IceToast** [comment]
This doesnt really make sense to me as the resources are still being allocated on pterodactyl.

**Comment by 1day2die** [comment]
if people want it, why not.
