### ISSUE TITLE
Notification System 

### ISSUE THREAD

**Issue by Hiekki4** [ControlPanel-gg/dashboard#106]
Make a system so that an administrator can send notifications to users

**Comment by anondev-sudo** [comment]
Good idea

**Comment by anondev-sudo** [comment]
It should be that admins can choose if they want to send email or notification on dashboard or both. And it should has title (subject) You have a new message from our staff team! and description should be the text admin has provided

**Comment by LogischJo** [comment]
This is implemented and will be added in the next stable release
