### ISSUE TITLE
Product Creation: 191 Char Limit in "Description"

### ISSUE THREAD

**Issue by NiktixNiktix** [ControlPanel-gg/dashboard#108]
**Describe the bug 🐛**
When you type 192 Letters in the Description Field on Product Creation and click submit you'll get an error 500

**To Reproduce**
1. Go to 'Products'
2. Click on 'Create New'
3. "Scroll" down to 'Description'
3.1. Write 192 Letters in Description
3.2. Click 'Submit'

**Expected behavior**
Maybe that it works but because of where the Description is shown i think it would be the best to limit the chars to an amount, so the Admin does not get an 500 ERROR and "Panics" ;) :)

**Screenshots**
Not needed, 

**Desktop (please complete the following information):**
 - OS: [Windows 11 ]
 - Browser [Opera (Chromium)]
 - Version [ooof idk at the moment... let me have a look... ... wait... ah there i found my browser version: 77.0.4054.172]

**Additional context**
I hope that that was a good bug report and easy to understand :) 👍

**Comment by AVMG20** [comment]
Very well documented 👍
Isseu fixed. thanks for letting us know
![image](https://user-images.githubusercontent.com/45005889/124510724-bf773d00-ddd4-11eb-99d6-1d2bedf68797.png)
