### ISSUE TITLE
Make Verify Buttons and resent Button More Prominent! [feature] 

### ISSUE THREAD

**Issue by NiktixNiktix** [ControlPanel-gg/dashboard#109]
# 🚀 Feature Request

### Is your proposal related to a problem?

My users are a bit Confused on how to verify their Account with Mail and Discord. The User gets the Hint to verify the Email-Adress. Right now it looks like this: "You are required to verify your email address before you can create a server." The user does not know, that a mail was already sent on his way and also have no option to sent the Verifaction mail again..

I know that if you wait a day or so, that then comes up a message, to resent the verifacation mail, but i think it is way to late! It should be right in the Error message on the Shop or when creating a server error message....

Furthermore, if they then click on the Button or the link in their email, they only get to the dashboard. There should also be an page that says, "Succesfully linked email" or so :)

After they now have susscesuffly linked their Email Adress, and try again to create a new server this message comes up: "You are required to link your discord account before you can create a server." But again, the user does not know, that he needs to click on his name, and go to profile to then link there their Discord...

And of Course i do know, you can disable the Force of Needed Verification, but anyways it is very important, that the user knows exactly what to do :)

### Describe the solution you'd like

In my comment :)

### Additional context

I do Think that this is really important for easy usage for the Enduser :)

**Comment by AVMG20** [comment]
reacted in discord, waiting for update :)

**Comment by NiktixNiktix** [comment]
Describe the solution you'd like

I think a good solution to this "problem" would be to display the buttons for "Verify Email" and "Link Discord" directly in these warning messages.

So:

The message "You are required to verify your email address before you can create a server." should then, right next to the "OK" button, be a new button which says something like "resend email". If you click this button, you should get a popup that says something like "Verification email resent, PLEASE CHECK YOUR SPAM FOLDER"

And when the user then clicks on the button in the mail or opens the link, the user should receive a confirmation that he has successfully verified their mail account.

The same principle for the Discord verification. In addition to the error message "OK" Button, add another Button which dircetly leads you to the DC login :)

I think this would be helpful for all users, for easier operation of the panel :)

I hope you understand what I mean :)

**Comment by AVMG20** [comment]
Very good suggestion :) very wel described. Thank you for your suggestion

**Comment by AVMG20** [comment]
Added a way for the user to see if his email has been verified by adding a simple icon next to his email on the profile page.
![image](https://user-images.githubusercontent.com/45005889/125188661-d8e51280-e234-11eb-8024-1e12b2ebaded.png)

Added 2 extra pop-ups on the profile page.
These pop-ups will be shown when the user still needs to do them, and the force config options are enabled.
![image](https://user-images.githubusercontent.com/45005889/125188703-0336d000-e235-11eb-887a-ae18ec88279f.png)

Hopefully this will be clear enough; for now, we will most likely look in the future into disabling access to the dashboard entirely when the user is required to verify their email first.

**Comment by NiktixNiktix** [comment]
> Added a way for the user to see if his email has been verified by adding a simple icon next to his email on the profile page.
> ![image](https://user-images.githubusercontent.com/45005889/125188661-d8e51280-e234-11eb-8024-1e12b2ebaded.png)
> 
> Added 2 extra pop-ups on the profile page.
> These pop-ups will be shown when the user still needs to do them, and the force config options are enabled.
> ![image](https://user-images.githubusercontent.com/45005889/125188703-0336d000-e235-11eb-887a-ae18ec88279f.png)
> 
> Hopefully this will be clear enough; for now, we will most likely look in the future into disabling access to the dashboard entirely when the user is required to verify their email first.


Could you place these Messages on the main page? because when i click on Create server, when i am not verifyied with email, then i just get the Error Message and i stay on the same page. I do not get redirected to the Profile page. So it would be usefull, to have it directly on the main page, so everone can see it very easily :)

**Comment by anondev-sudo** [comment]
Also in profile you should see your Discord tag and avatar from account that is linked. https://github.com/ControlPanel-gg/dashboard/issues/125

**Comment by AVMG20** [comment]
solved
