### ISSUE TITLE
First and last name on the account creation 

### ISSUE THREAD

**Issue by Hiekki4** [ControlPanel-gg/dashboard#111]
Add fields to the client when creating account add the first and last name, so that if the pterodactyl e-mail is active the welcome message does not get strange.

**Comment by anondev-sudo** [comment]
This is really good idea, or maybe put Discord user tag as last name when user has verified Discord

**Comment by AVMG20** [comment]
Please use the template we provide for issues hiekki4, good suggestion

**Comment by j122j** [comment]
The first and last names will be removed in pterodactyl v2. So no reason to add this just for pterodactyl, however, we could add this as part of billing information.

Source: https://github.com/pterodactyl/panel/blob/v2/database/migrations/2021_07_29_032255_yeet_names_from_users_table.php
