### ISSUE TITLE
Bash script/cmd to change/install ptero to the controlpanel dash

### ISSUE THREAD

**Issue by DylanGS9** [ControlPanel-gg/dashboard#112]
# 🚀 Feature Request

### Is your proposal related to a problem?

no

### Describe the solution you'd like

Bash script renaming/redoing all files that have any relation to pterodactyl panel, so upgrading won't create problems if on an existing pterodactyl installation.

### Additional ideas

Maybe just delete all files except for existing node info/servers, rename anything in relation to pterodactyl, and install the latest version of dashboard.

**Comment by RamonRobben** [comment]
@DylanGS9 Why do you need this? You can just install the dashboard after you have installed pterodactyl. I think you can even do it the other way around. Are you facing any issues upgrading?

**Comment by DylanGS9** [comment]
No, It would be useful for people who aren't familiar with linux however, and can solve potential compatibility issues, i.e pterodactyl having something this panel doesn't, or the other way around.
