### ISSUE TITLE
Trade credits for $ 

### ISSUE THREAD

**Issue by DylanGS9** [ControlPanel-gg/dashboard#113]
# 🚀 Feature Request

### Is your proposal related to a problem?

No

### Describe the solution you'd like

Somewhere in the panel (maybe it's own location, I haven't been able to test anything yet), a button to trade credits for cash thru paypal. The admin can enable/disable this, make limits, set a timeout and/or admin approval, and set a price for each credit. Like for example if i wanted 1 credit to = 1$. It'd send the 1$ upon completion, removing the 1$ from the set paypal address (owners/admins). to the users paypal address that'd be set. Maybe could be implemented with bitcoin if an API would allow. 

### Additional context

None

**Comment by RamonRobben** [comment]
@DylanGS9 Why would you want this? Why do you want to let users cash out credits? Please give some more information on why you need or want this feature.

**Comment by DylanGS9** [comment]
> @DylanGS9 Why would you want this? Why do you want to let users cash out credits? Please give some more information on why you need or want this feature.

If for example someone bought more credits than planned, it's ALOT easier to do it on the panel than manually set the price of a credit in order to send refunds. Like i suggested it should be decided by admins whether it'd be enabled or disabled, with variables set ofc. Plus, if someone wanted to give customers some $$ rewards, it'd be alot easier. From an adminstration pov, this takes out lots of potential hassles.

**Comment by AVMG20** [comment]
> > @DylanGS9 Why would you want this? Why do you want to let users cash out credits? Please give some more information on why you need or want this feature.
> 
> If for example someone bought more credits than planned, it's ALOT easier to do it on the panel than manually set the price of a credit in order to send refunds. Like i suggested it should be decided by admins whether it'd be enabled or disabled, with variables set ofc. Plus, if someone wanted to give customers some $$ rewards, it'd be alot easier. From an adminstration pov, this takes out lots of potential hassles.

You don't need to set a price for a credit when the user wants a refund. You can literally see what packages they have purchased and see how many credits they have gotten and the price for this. On top of that, users can also request a charge back through PayPal to get their money back if they are not happy with the purchase they've made. There are no credit based services (that I know of) that allow you to swap back your credits to money. I honestly don't see a good use for this. I think it requires alot of work for something I assume won't get used by nearly any host.

Ofc you are free to implement this for your own host. This isn't something I would be adding to controlpanel in the near feature.

**Comment by anondev-sudo** [comment]
This should be closed
