### ISSUE TITLE
Extensions + Configurable themes.

### ISSUE THREAD

**Issue by broimsuperman** [ControlPanel-gg/dashboard#114]
# 🚀 Feature Request

### Is your proposal related to a problem?

No
### Describe the solution you'd like

An environment/ecosystem/page for system administrators to easily add extensions and themes. the themes would switch from the set css, to the themes css, and potentially other files if needed. the extension upgrade would be pretty hard obviously, but it could make development, SO MUCH EASIER, we could develop extensions, buy and sell, create marketplaces, etc. For example: oath extensions, notifs, custom formatting, uis, permission management/tiers (admin, owner), etc

### Additional context

Maybe take an approach like flarum. More details here:

https://discuss.flarum.org/t/extensions
https://flarum.org/

**Comment by RamonRobben** [comment]
@DylanGS9 This is certainly something that's on our todo list. It's just that we will look into it once the panel is more stable in terms of code changes. Otherwise we would have to re-implement this plugins system every time we do major changes.

**Comment by 1day2die** [comment]
v1
