### ISSUE TITLE
Captcha on login page

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#117]
Add captcha on login page.

Also can you add optional support for hcaptcha instead of google recaptcha? So you can choose provider which you prefer.

**Comment by AVMG20** [comment]
I will add the captcha to the login page. That's a good point!

I won't be adding support for multiple captchas in a while as I think it doesn't really matter much, and it works now with google ReCaptcha, the same way ptero does it, so it matches.

**Comment by anondev-sudo** [comment]
I prefer hcaptcha because you can also earn some little money from it and withdraw it to paypal or you can give it to charity.

**Comment by anondev-sudo** [comment]
And also captcha should be on reset password page
