### ISSUE TITLE
Make a system to sell servers

### ISSUE THREAD

**Issue by Hiekki4** [ControlPanel-gg/dashboard#118]
Make a system to sell servers, many people prefer it this way and it gets simpler for the client, instead of having to buy credits and then create the server, could be buy the server and is created at the same time.

**Comment by FlaringPhoenix** [comment]
We would have to redo a lot of the dashboard for this to be added. This was created with a credit system and I believe that it will stay that way.

**Comment by LogischJo** [comment]
Anyways, I guess that adding an page - if you subscribe a server which tells you how much credits you need to run it an whole month and offers you the way to buy this custom number of credits directly it would be easier for clients
