### ISSUE TITLE
Endpoint to add credits

### ISSUE THREAD

**Issue by Hiekki4** [ControlPanel-gg/dashboard#121]
Endpoint to add credits to the user, because only exists to update the number of credits not to add

**Comment by AVMG20** [comment]
Yea is something I wish to add aswel, please make use of our issue templates however :)

**Comment by somerandomcloud** [comment]
This is a pretty easy thing to add to your code temporarily until AVMG adds it. Just call the userinfo endpoint, get the credits amount, and sum the amount you wish to add, and update.

**Comment by Hiekki4** [comment]
That's what I did.
