### ISSUE TITLE
[feature] 

### ISSUE THREAD

**Issue by mrnitr0** [ControlPanel-gg/dashboard#122]
# 🚀 Feature Request

extensions Like ( Proxmox, Plesk, Directadmin, Domain registerers)
And Option for Dark-Light Mode
Other payment methods like stribe, 2checkout

**Comment by AVMG20** [comment]
Please make seperate issues for each feature. I believe there is already an issue for more payment methods. Currently our entire code base is designed for pterodactyl  and we currently have no desire to make the new whmcs. However if we get more contributors we can certainly look into having a broader controlpanel. But as of right now it's not doable with the workforce we have.
