### ISSUE TITLE
Show who has redeemed vouchers

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#126]
Im admin area for vouchers there should be that you can see who has redeemed that voucher, just make to display username with link to user (/admin/user) in admin area

**Comment by 1day2die** [comment]
Heyo,

why?

**Comment by LogischJo** [comment]
For example to detect abuse

**Comment by 1day2die** [comment]
Then it should log the IP and not the username?

**Comment by redstonedesigner** [comment]
That may cause issues with regard to data protection.  I think showing the username and time would be better.

**Comment by anondev-sudo** [comment]
Yes that's enough to show username, and when you click on it, redirect to user info page

**Comment by LogischJo** [comment]
An PR was made for it
