### ISSUE TITLE
Notification Options (Mark as Read/Delete)

### ISSUE THREAD

**Issue by William071802** [ControlPanel-gg/dashboard#131]
It would be incredible if we could mark notifications as read from within the notification bell's popout.
I would also love to see an option to bulk select and mark them as read or delete them within the notification page

**Comment by anondev-sudo** [comment]
Will be this implemented in next updated when you have added manual notifications?

**Comment by 1day2die** [comment]
PR for this is open

**Comment by anondev-sudo** [comment]
There isn't button to delete old notifications that you don't need
