### ISSUE TITLE
500 | Server Error on Duplicate Voucher

### ISSUE THREAD

**Issue by NiktixNiktix** [ControlPanel-gg/dashboard#133]
**Describe the bug 🐛**
When you want to Create an Voucher, which already exists, meaning that the Code is already used as an Voucher, then you will get a SERVER 500 Error.

**To Reproduce**
1. Go to 'Vouchers'
2. Click on 'Create New'
3. Fill in all Fields
4. Click on 'Submit'
5. Create another Voucher with the SAME Code and Click submit

**Expected behavior**
Just a simple Message, that that code already exists and cannot be created again. 

Just Maybe a Button that asks if you want to override the existing Voucher with this new Voucher, that would be a nice small addition, but not necessary needed :)

**Screenshots**
Not Needed 

**Desktop (please complete the following information):**
 - OS: WIndows 11
 - Browser Opera - Chromium Based
 - Version Browser Version is: 77.0.4054.172

**Comment by AVMG20** [comment]
solved
