### ISSUE TITLE
Limit Product Quantities

### ISSUE THREAD

**Issue by William071802** [ControlPanel-gg/dashboard#135]
It would be incredibly useful to be able to limit the amount of each product type that can be created in order to prevent over allocating resources when you have more than one type

**Comment by 1day2die** [comment]
Overlocating is not possible if your ptero is setup correctly.

**Comment by 1day2die** [comment]
i got pretty far doing this and its actually quite easy and quickly done, but sadly i dont know shit about JS and the server creation part is fully written in JS so i cannot continue working :/

**Comment by 1day2die** [comment]
@AVMG20  @IceToast  ?

**Comment by GeckoBoy84** [comment]
Overallocation is no longer possible
