### ISSUE TITLE
[feature] Donating Rewards

### ISSUE THREAD

**Issue by GeckoBoy84** [ControlPanel-gg/dashboard#139]
# 🚀 Feature Request

### Is your proposal related to a problem?

You have to manually add extra rewards for donating x amount.

### Describe the solution you'd like

Would be nice to have the ability to set extra rewards for donating x amount of money.

### Additional context

You could rewards credits, RAM, CPU, Backups, Server Slots etc

**Comment by AVMG20** [comment]
In our paypal store you can set whatever price on the amount of credits. You can give increasingly more credits the higher the amount. Donating is gifting. This would be selling and is already implement. We work with a product based system. Added just a bit of ram on a server will require a new product for thos server to be tracked, a bit of a limitation with the system, we are also not a dashatyl copy 📦

**Comment by GeckoBoy84** [comment]
I meant something else. For example, if they accumulate £100 spent for example, they could receive more slots than someone donating just £5 etc
