### ISSUE TITLE
[feature] Server slots for credits

### ISSUE THREAD

**Issue by GeckoBoy84** [ControlPanel-gg/dashboard#140]
# 🚀 Feature Request

### Is your proposal related to a problem?

Currently people have to buy additional server slots with money.

### Describe the solution you'd like

Would be nice to be able to sell server slots for credit.

**Comment by anondev-sudo** [comment]
Not for money directly, but for credits

**Comment by Experimentali** [comment]
Thus I believe is done

**Comment by 1day2die** [comment]
oh right,. nice!
