### ISSUE TITLE
Allow Manual Notifications/Emails

### ISSUE THREAD

**Issue by William071802** [ControlPanel-gg/dashboard#142]
As stated by @anondev-sudo -
"Admins [could send] notifications to users on dashboard or using API. There should be also that you can choose if you want to send just notification on dashboard or just email notification or both."

_Originally posted by @anondev-sudo in https://github.com/ControlPanel-gg/dashboard/issues/136#issuecomment-882081973_

**Comment by LogischJo** [comment]
This is implemented and will be added in the next stable release
