### ISSUE TITLE
[Bug Report] SSH Account Credit Amount

### ISSUE THREAD

**Issue by GeckoBoy84** [ControlPanel-gg/dashboard#143]
**Describe the bug 🐛**
When you create an account **from SSH**, the account always has 200 credits, not the default amount.

**To Reproduce**
1. Go to console
2. Create a user
3. Log in to controlpanel.gg
4. You have 200 credits

**Expected behavior**
The user to have the default amount of credits.

**Comment by somerandomcloud** [comment]
Uh I don't exactly see what the problem is? I don't think any host would be creating accounts via ssh instead of the registering page....

**Comment by AVMG20** [comment]
these values are hardcoded, the only purpose of this command is to make your initial admin account
