### ISSUE TITLE
[feature] Billing Cycle

### ISSUE THREAD

**Issue by GeckoBoy84** [ControlPanel-gg/dashboard#145]
# 🚀 Feature Request

### Is your proposal related to a problem?

I dont want people with small amounts of Credits to be able to access my most expensive plans.

### Describe the solution you'd like

Ability to change the charge increment. Could be x hours, x days, x weeks and x months with the ability for the amount to be 0.

**Comment by somerandomcloud** [comment]
This should be labeled as urgent, because this can be abused HARD

**Comment by GeckoBoy84** [comment]
It has definitely been abused on my host!

**Comment by anondev-sudo** [comment]
Hourly billing system is great, if you will change it for example to monthly, you will be billed at the month, and you could just delete the server before month has passed and you won't be billed.

Instead of that you can specify that you can choose minimum required credits for every product, if product cost 50 credits monthly, you set minimum required credits to 50 and then users who don't have at least 50 credits won't be able to make server with this product, error message will be showed.

**Comment by GeckoBoy84** [comment]
Take the credits after 30 days of creating (including the day you purchase)

**Comment by AmoxAmox** [comment]
I think adding the option to specify whether the product can be billed hourly or monthly will be more better, like if the product is billed monthly the user can have an option to "cancel the subscription" instead of "deleting" option.

**Comment by anondev-sudo** [comment]
> I think adding the option to specify whether the product can be billed hourly or monthly will be more better, like if the product is billed monthly the user can have an option to "cancel the subscription" instead of "deleting" option.

And when the user has cancelled the subscription when user has 3 days till next billing date, will the server be deleted, or it will be deleted after 3 days (when there is next billing date)?

**Comment by Dqgs** [comment]
> > I think adding the option to specify whether the product can be billed hourly or monthly will be more better, like if the product is billed monthly the user can have an option to "cancel the subscription" instead of "deleting" option.
> 
> And when the user has cancelled the subscription when user has 3 days till next billing date, will the server be deleted, or it will be deleted after 3 days (when there is next billing date)?

I think that it should be immediately deleted if there is no option to get back the server

**Comment by Dqgs** [comment]
> Hourly billing system is great, if you will change it for example to monthly, you will be billed at the month, and you could just delete the server before month has passed and you won't be billed.
> 
> Instead of that this should be added: you can specify minimum required credits for every product, if product cost 50 credits monthly, you set minimum required credits to 50 and then users who don't have at least 50 credits won't be able to make server with this product, error message will be showed.

I think another option could be just take credits away immediately for the month and give people back credits that they haven't used for the month so like ex 500 credits a month 15 days in 250 credits. But i feel as though this should be optional to give credits back or not as some people may want a 1 month contract.

**Comment by anondev-sudo** [comment]
Too complicated, hourly billing is great, just make feature that when you create server, credits for the first hour will be removed immediately. This has higher prio, together with option to set minimum required credits per product.

In the future custom billing cycle may be added too.

**Comment by tovade** [comment]
maybe make it when the user creates the server it directly deletes the credits from he's account and not at the end of the month.

**Comment by Bazimek** [comment]
> maybe make it when the user creates the server it directly deletes the credits from he's account and not at the end of the month.

Yes, this. Hourly billing can be too much abused

**Comment by Dqgs** [comment]
Personally i love the idea of credits but i feel as though there should be a option to also just purchase servers

**Comment by anondev-sudo** [comment]
This system gives you option that you can cancel your server anytime and there is suggestion to add option to change server plan too

**Comment by 1day2die** [comment]
Min. Credits option
