### ISSUE TITLE
[feature] Change plan after creation

### ISSUE THREAD

**Issue by GeckoBoy84** [ControlPanel-gg/dashboard#146]
# 🚀 Feature Request

### Is your proposal related to a problem?

Users lose their servers if they run out of coins.

### Describe the solution you'd like

Ability to be able to edit the plan after creation. For example if they win credits, they will want to spend them, however if they then don't purchase any, they cannot use their server unless they buy credits or win more.

**Comment by AVMG20** [comment]
#74 duplicate issue
