### ISSUE TITLE
Modify Verification Descriptions

### ISSUE THREAD

**Issue by William071802** [ControlPanel-gg/dashboard#147]
We just launched and had a user point out: Currently if a host doesn't want to give free credits upon a user verifying it'll say:
"Please verify your email address to get 0 credits and increase your server limit to 0
You can also verify your Discord account to get another 0 credits and increase your server limit again with 0"

This makes us look pretty bad. Would be nice if it were either customizable or simply different (friendlier) when the value(s) are set to 0.

**Comment by AVMG20** [comment]
Good point
