### ISSUE TITLE
[feature] Custom roles

### ISSUE THREAD

**Issue by somerandomcloud** [ControlPanel-gg/dashboard#157]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

Not really

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

A good feature that could be very beneficial is to be able to create custom roles on the panel, just to label certain users. Id attempt to make this myself but _php_

**Comment by anondev-sudo** [comment]
Good idea

**Comment by anondev-sudo** [comment]
But if admins will be able to write custom notes to user details, it will solve your issue I think. Those notes should be visible just to admins when they are viewing user details

**Comment by 1day2die** [comment]
What exactly would this be for? Why would i label users?

**Comment by somerandomcloud** [comment]
To seperate people like discord server boosters and actual donators

**Comment by 1day2die** [comment]
hi, 

can we come back to this?
Do the roles need special permissions in the Panel or is this only for labeling and "grouping" users?

**Comment by ayodev-in** [comment]
Yes, it would be nice if it's possible

**Comment by 1day2die** [comment]
> Yes, it would be nice if it's possible

if what is possible? i asked 2 questions there^^

**Comment by ayodev-in** [comment]
> > Yes, it would be nice if it's possible
> 
> if what is possible? i asked 2 questions there^^

Uh, it would be nice if it's possible to get the role to special permissions and at sidebar it would show how many members are online or just total members

**Comment by 1day2die** [comment]
Permissions...like?

**Comment by 1day2die** [comment]
ill look into this. Will however only include labeling with a name and different colored badges.

**Comment by somerandomcloud** [comment]
Yeah, I feel that adding custom permissions would be way more difficult than it should be kek
If possible, can you also make it so that its possible to add and remove roles with the api? And possibly create them. Not sure what you have in mind tho

**Comment by j122j** [comment]
Definitely possible, if we are going to add roles and permissions we will probably use [laravel-permission](https://spatie.be/docs/laravel-permission/v5/introduction)

**Comment by LogischJo** [comment]
> Definitely possible, if we are going to add roles and permissions we will probably use [laravel-permission](https://spatie.be/docs/laravel-permission/v5/introduction)

That’s what AVMG talked about before already if I remember correctly

**Comment by somerandomcloud** [comment]
Never saw AVMG mention it, but very good idea!

**Comment by 1day2die** [comment]
i dont see any need for other permissions than admin tbh xD im keen on finding out

**Comment by j122j** [comment]
> i dont see any need for other permissions than admin tbh xD im keen on finding out

It is useful if you have multiple support members, they should be able to access servers, users, and vouchers, but there is no reason for them to be able to edit products, configuration, or create API keys.

**Comment by 1day2die** [comment]
v1
