### ISSUE TITLE
Minum Credits per Product[feature] 

### ISSUE THREAD

**Issue by NiktixNiktix** [ControlPanel-gg/dashboard#161]
# 🚀 Feature Request

First of all, i am pretty sure that i have already seen that Feature Request Somewhere, so sorry if this is a Duplication, i couldn't find it right now...

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

Lets say i have 20 Credits and i have a plan for 1 Credit / Hour. I could totally buy that.. But what happens if i have a plan for 50 Credits / Hour? Maybe something more Premium? Then the user could Create the Expensive server (because he doesn't need to pay at creation) can use the server for one hour and than the server suspends. So he had like one hour of free server.

Of couse you could fix that with setting the Minium Credits to 50 but then he could not buy the Product which costs 1 Credit / Hour

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

An Option for Every Product to set the Minimum Credits needed to create an server :)

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

I discussed on that issue with @${j122j} on discord :)

**Comment by Bazimek** [comment]
Yes, this is connected for the pay per egg. I really want that function too, or make configurable setting for immidiately charged up the credits for the server. Please.

**Comment by 1day2die** [comment]
Pull-Request opened
