### ISSUE TITLE
Refferal System[feature] 

### ISSUE THREAD

**Issue by NiktixNiktix** [ControlPanel-gg/dashboard#162]
I think this is a big and Complicated Feature Request...

# 🚀 Feature Request

### Is your proposal related to a problem?

No it is not related to a problem tecnically...

### Describe the solution you'd like

I wanted to have an Refferal System. So on admin UI you have an own Page (like Products, Servers, Users and so on...) which is called something like Refferal System. There you can create an custom Link and assign that link to an User Account. Also you should be able to set an Percentage amount of how much Provision you want to give .

When now a customer clicks on that link, an cookie is placed for a set amount of time and then if the Customer buys Credits, the Set User will get the Percentage amount of Credits...

I hope it is understandable what i mean, if not reply to the issue, i am open to further explain the idea when there are questions :)

**Comment by LogischJo** [comment]
I would prefer to have an enter Referral code field while ordering new coins or servers instead of placing an cookie but all in all an nice suggestion.

**Comment by NiktixNiktix** [comment]
> I would prefer to have an enter Referral code field while ordering new coins or servers instead of placing an cookie but all in all an nice suggestion. 

this is also a very good idea! But i would love to see this Feature! Because i do think, that that boosts the Users for the Hosting, because more Networks wants to recommend the Hosting :)

**Comment by RamonRobben** [comment]
@NiktixNiktix I agree with @LogischJo
Instead of only using a cookie I would make a referral link field where you can fill in the referral.
If a user has a referral cookie you can autofill the field to make it simpler for the user.

**Comment by anondev-sudo** [comment]
I have already suggested that here https://github.com/ControlPanel-gg/dashboard/issues/44
