### ISSUE TITLE
More api endpoints

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#168]
Make api endpoints for creating users, servers, updating servers, getting all purchases, getting purchases of certain user.

**Comment by anondev-sudo** [comment]
Api endpoints for purchases are already suggested here https://github.com/ControlPanel-gg/dashboard/issues/166, should I close it?

**Comment by somerandomcloud** [comment]
Why did you make duplicate issues is what I am asking myself... And you didnt even use the template on this issue.

Yes, close this issue
