### ISSUE TITLE
A referral system for controlpanel.gg

### ISSUE THREAD

**Issue by r-kjha** [ControlPanel-gg/dashboard#169]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

I want to suggest a referral system for controlpanel.gg when clients will get their referral link eg: dash.demo.com/ref?=user_name and he/she can send it to other people. And when someone uses his link to signup and makes the first purchase, The referer gets a certain percentage of the credit he purchased (% can be configured in configuration).

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Should I write the same thing here? Simply a referral system where clients get their own personal link and when someone uses that link to signup and makes a purchase the referer gets x% of the total credit purchased.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

Vultr and digital ocean has referral program where when people signup using a referral link they get 100$ credit for 1 month and the referer get 25$ credit for each refer

**Comment by AVMG20** [comment]
duplicate #162
