### ISSUE TITLE
Sync servers button

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#170]
There should be Sync servers button in admin area, that will fetch ptero api and update server details for all servers in database so server names, descriptions, state, feature limits will be actual on dashboard.

Why?
When user rename server on panel, it's not renamed in dashboard and users are telling that it's not good when the name and other details are not updated.

**Comment by AVMG20** [comment]
feature limits are set by the product, we can't `sync` them if you changed them manually on ptero. the only thing that would need matching is server names (description will be set to product desc in the upcoming updates)

**Comment by anondev-sudo** [comment]
Ok, just sync server name and description, and if ptero api endpoint returned 404 error when fetching server, delete it from dashboard.

**Comment by anondev-sudo** [comment]
I have suggested that admins can create servers for users with custom specs, eggs, monthly price here https://github.com/ControlPanel-gg/dashboard/issues/65

**Comment by AVMG20** [comment]
> I have suggested that admins can create servers for users with custom specs, eggs, monthly price here #65

I fail to see how this is related to the current issue

**Comment by anondev-sudo** [comment]
> > I have suggested that admins can create servers for users with custom specs, eggs, monthly price here #65
> 
> I fail to see how this is related to the current issue


It's related to this problem:

> feature limits are set by the product, we can't sync them if you changed them manually on ptero.

**Comment by 1day2die** [comment]
@AVMG20  shouldnt this be -almost- the same logic as the Sync Button on /admin/nodes

**Comment by anondev-sudo** [comment]
Yes, it should just sync server name and descriptions in database. When server was deleted on panel, delete it from dashboard database too

**Comment by ok236449** [comment]
Automatic name syncing done in [PR570](https://github.com/ControlPanel-gg/dashboard/pull/570). Server description does not have to be synced, as it is empty by default on both CP and Ptero.
