### ISSUE TITLE
[feature] Configurable what users can do (delete own servers etc)

### ISSUE THREAD

**Issue by Bazimek** [ControlPanel-gg/dashboard#172]
# 🚀 Feature Request

Give us please configurable option to settings tab for disabling possibilty for users to delete their own servers. I don't like the fact they can delete and create a new one whenever they want, because the coins are not immidiately charged up after server is created.

**Comment by AVMG20** [comment]
A solution we wanted to add is a config option that allows you to charge the first hour in advance as some sort of creation cost. Removing the ability for users to delete their own servers is not something we're keen on, sonce this billing platform is ment to give the client alot of flexibility.

**Comment by Bazimek** [comment]
Yes, but if every owner can congirue that so everyone can choose what they want. I dont mean to force disable deletion, but make it configurable.

**Comment by anondev-sudo** [comment]
I don't think that this is really needed, permission system for users. Even ptero does not have this.

**Comment by anondev-sudo** [comment]
> A solution we wanted to add is a config option that allows you to charge the first hour in advance as some sort of creation cost.

This will fix your issue @Bazimek
