### ISSUE TITLE
Form data casting

### ISSUE THREAD

**Issue by j122j** [ControlPanel-gg/dashboard#174]
**Describe the bug 🐛**
When updating a number value with API, it will be set as a string in the response.

**To Reproduce**
1. Make a POST request to /api/users/<id> and update any number value
2. Value will be a string.

**Expected behavior**
The value should be a number.

**Screenshots**
https://cdn.j122j.me/files/5b9b71e4.png

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave
 - Version: development branch

**Comment by somerandomcloud** [comment]
Uhhh when you update the api, you probably updated the value as a string and not as a number

**Comment by j122j** [comment]
> Uhhh when you update the api, you probably updated the value as a string and not as a number

API uses form data. Form data only accepts strings, anyways even if I did supply a string it should cast it to a number.

**Comment by somerandomcloud** [comment]
From my experience, I could also send in an integer...

**Comment by 1day2die** [comment]
Pull-Request opened
