### ISSUE TITLE
[feature]  OATH support aka, oath2

### ISSUE THREAD

**Issue by snaildos** [ControlPanel-gg/dashboard#175]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

When hosts get larger, we want to evolve into our own portal system, with Oath2.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Being able to disable the login form, so it doesnt ask for your username and password and force to "Login with [whatever the oath2 domain is]".

Oath2 is a powerful tool and hopefully this get's added!

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

Nope.

**Comment by anondev-sudo** [comment]
Good idea, add option that Discord oauth button will be showed on login/register page

**Comment by snaildos** [comment]
Ye. Not just discord. Other path providers. :)

**Comment by anondev-sudo** [comment]
Why wontfix?
