### ISSUE TITLE
[feature]  ticket system

### ISSUE THREAD

**Issue by nickdevnl** [ControlPanel-gg/dashboard#176]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

no

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

make a ticket system on the dashboard will be good for bigger hostings so staff don't have a messey discord server

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

no

**Comment by RamonRobben** [comment]
@nickdevnl Yeah I almost also suggested this some time ago. But I couldn't decide wether it would it within the scope of the application or not. It's quite a big task to implement a ticket system + permissions. I was also thinking of using a 3rd party ticket / live chat system and just implement that in a page but I guess this is something that needs to be discussed more.

**Comment by nickdevnl** [comment]
it should be handled within the website tho idk if thats possible.
its a big thing to make but its better to handle for staff.

**Comment by anondev-sudo** [comment]
Good idea. There should be support tickets in the dashboard.

**Comment by 1day2die** [comment]
next release
