### ISSUE TITLE
Sorting of tables doesn´t work

### ISSUE THREAD

**Issue by BolverBlitz** [ControlPanel-gg/dashboard#177]
**Describe the bug 🐛**
Sorting isn´t working as expected

**To Reproduce**
1. Go to any table with sorting and click sort.

**Expected behavior**
Sorting numbers should result in 100, 200, 300, 400 and not 200, 100, 400, 300

**Screenshots**
![grafik](https://user-images.githubusercontent.com/35345288/131163396-449e0ed4-89c6-4587-bd4f-5760bef05bd8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10, 64Bit 20H2
 - Browser Firefox 91.0.2 (64-Bit)  / Chrome 92.0.4515.159 (Offizieller Build) (64-Bit)
 - Version 0.4.2

**Comment by AVMG20** [comment]
mmm I can't get this behaviour replicated

**Comment by ok236449** [comment]
On the screenshot, it shows you are sorting by name (which you really are). The arrow icons are shifted way too much to the right so it looks like it corresponds to a different place. (It looks the same on my copy of dashboard.) If I can suggest, put the arrow icons right next to the text it belongs to.

**Comment by BolverBlitz** [comment]
Thanks @ok236449 i totaly didn´t see that. Thanks for the tip. 
  
  
`If I can suggest, put the arrow icons right next to the text it belongs to.`
>Yes, absolutly. The current version isn´t clear abotu that
