### ISSUE TITLE
Chancing icons won´t store the new uploaded icon.

### ISSUE THREAD

**Issue by BolverBlitz** [ControlPanel-gg/dashboard#178]
**Describe the bug 🐛**
New icons won´t get saved.

**To Reproduce**
1. Go to Setting
2. Click on Trashbin of the current icon
3. Upload new Icon
4. Press Submit
5. Press CNTRL + F5 / Restart Browser / Whatever to clear cache
6. Enjoy default icon because it didn´t chance to the new one.

**Expected behavior**
Saving the new Icon.

**Screenshots**
Could only be shown in a gif.

**Desktop (please complete the following information):**
OS: Windows 10, 64Bit 20H2
Browser Firefox 91.0.2 (64-Bit) / Chrome 92.0.4515.159 (Offizieller Build) (64-Bit)
Version 0.4.2

**Comment by AVMG20** [comment]
have you made the symlink between storage and public?

**Comment by BolverBlitz** [comment]
Yes

**Comment by 1day2die** [comment]
Bug is easy to reproduce. Someone should look into that

**Comment by j122j** [comment]
It wasn't working for me, but it turns out I just didn't have the symlink. After that, it worked.
Dashboard icon updated automatically, favicon updated in storage but didn't update in the browser due to cache.

Also https://controlpanel.gg/docs/Installation/getting-started#set-permissions

**Comment by AVMG20** [comment]
fixed

**Comment by BolverBlitz** [comment]
#279
