### ISSUE TITLE
[feature] Charge credits on server deletion

### ISSUE THREAD

**Issue by j122j** [ControlPanel-gg/dashboard#179]
# 🚀 Feature Request

### Is your proposal related to a problem?

If someone makes a server and deletes it before an hour has gone by they won't be charged. This is not a huge issue, however, I still think it can be abused.

### Describe the solution you'd like

An easy solution to this problem is just to charge the hourly price when a server is deleted. This way they are charged even if they didn't use the whole hour, for example only 10 minutes, this is what some other companies do.

**Comment by anondev-sudo** [comment]
Or charge for the first hour when you create a server, it will be easier to add I think

**Comment by AVMG20** [comment]
I think charing servers the first hour on creation is a bit easier; this way ppl won't walk into negative credits (which can't be stored)

**Comment by AVMG20** [comment]
Charges the first hour worth of credits upon creating a server. has now been added
