### ISSUE TITLE
Gaining credits by voucher doesn´t unsuspend servers

### ISSUE THREAD

**Issue by ok236449** [ControlPanel-gg/dashboard#182]
Gaining credits by voucher or directly by admin modifying account details doesn´t unsuspend servers. They stay suspended.

1. Make testing account
2. Create a server, wait till you run out of credits and the server suspends.
3. use a voucher or ad credits to the user
4. The servers stay suspended

Expected behavior:
The server should be accessible again.

Screenshots:
![image](https://user-images.githubusercontent.com/89067167/132565800-11a8c50a-53fc-4281-b22c-d8aef437587f.png)

![image](https://user-images.githubusercontent.com/89067167/132565905-7207b735-7089-4a94-8546-4f01ed1839f8.png)

Haven´t tested if it works when purchased by PayPal.
Maybe a refresh button would be handy.
I also don´t know what the Database button does.

**Comment by AVMG20** [comment]
good point!
