### ISSUE TITLE
[feature] 

### ISSUE THREAD

**Issue by shawn3308** [ControlPanel-gg/dashboard#184]
# 🚀 Feature Request

### Is your proposal related to a problem?

 about the backup system in pterodactyl because once the server is suspended the backups don't get deleted so it would be good if you add the auto deleting of the files

### Describe the solution you'd like

I would like to see when the server is suspended all the backups which were taken on that server also delete with the suspended server

### Additional context

When the server gets suspended don't right away through the backup just keep it for like two days and then delete the backup

Regards 
Coconut  ^^

**Comment by anondev-sudo** [comment]
If you delete server from dashbosrd with button, please add that backups and databases will be deleted firstly, and then the server will be deleted

**Comment by shawn3308** [comment]
So its there Right ?

**Comment by AVMG20** [comment]
Why delete backups when a suspended server can be unsuspended by the user by paying? It seems kind of harsh

**Comment by AVMG20** [comment]
Also, auto-deleting the server itself isn't a thing yet ( something that will be added ), so this is already very far stretched. I don't see how this is an issue?
