### ISSUE TITLE
[feature] Renew System(30days)

### ISSUE THREAD

**Issue by AsadullahMuhammad** [ControlPanel-gg/dashboard#187]
An option for the server to automatically be suspended after 30days if user does not have enough credits to renew his plan.

**Comment by anondev-sudo** [comment]
> The control panel uses a credit-based system.
credits are charged hourly based on the monthly price (price / 30 / 24)
This means that the price of your products won’t be charged right away when the user creates a server, but instead, the credits are reduced hourly—giving the user the option to cancel and create servers freely anytime.
When the user runs out of credits, his server will automatically be suspended.
