### ISSUE TITLE
Add the tax to checkout

### ISSUE THREAD

**Issue by ok236449** [ControlPanel-gg/dashboard#189]
# 🚀 Feature Request

Add tax settings. This way it could calculate tax before making a purchase and the buyer will pay for the tax.

This morning a client bought credits for about 1€ and I received only like 0.6€. So the tax was payed from my side. I want to be able to select, if they buy a small option (like the 1€) so that they pay actually 1.5€ and I received the full price of 1€.

There is already a tax field at checkout, but it is 0.

**Comment by RamonRobben** [comment]
You can use this tool to calculate how much in total you need to ask to cover paypel fees + taxes.
At least where I live you need to show amounts in full which means including taxes and fees if possible.
PayPal has a default fee of 3,4% of the amount + 0,35 cents. And your country might probably ask for like 21% tax to be witheld.
https://www.salecalc.com/paypal?p=1.00&l=nl&r=0&e=0&f=0&m=2&c=0

**Comment by ok236449** [comment]
Yes, but how can I make it show here?
![IMG_20210916_145308](https://user-images.githubusercontent.com/89067167/133615508-ff0a1ed1-2e1c-4be6-a0d7-52c99e3e4e0c.jpg)

**Comment by 1day2die** [comment]
PR Opened.

**Comment by 1day2die** [comment]
Merged
