### ISSUE TITLE
Pause server button for users

### ISSUE THREAD

**Issue by myCenter-docs** [ControlPanel-gg/dashboard#192]
# 🚀 Feature Request

Add a button for normal users, to pause their server. This is basically the same as suspending a server but the user is pausing it themselves. This prevents them from accessing their server, and it doesn’t charge the user for having the server. This is so if someone knows they’ll need the server in x days, and they don’t want to lose the files, they can pause it so it doesn’t charge them

**Comment by AVMG20** [comment]
duplicate #104
