### ISSUE TITLE
[feature] 

### ISSUE THREAD

**Issue by BamseMoms** [ControlPanel-gg/dashboard#193]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

I want that the customer can add more ram to the server..

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

I want that the customer can add more ram to the server../ mby api can chnage this if a customer buys more RAM(GB)

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by AVMG20** [comment]
already requested
