### ISSUE TITLE
discord Oauth error

### ISSUE THREAD

**Issue by ItzKazuki** [ControlPanel-gg/dashboard#194]
**Describe the bug 🐛**

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_29](https://user-images.githubusercontent.com/79141593/133918060-d7e10bc3-cf35-42ea-9a92-148f932868a0.png)

![Screenshot_30](https://user-images.githubusercontent.com/79141593/133918483-4ff718d4-ef98-4802-956a-f0e291623865.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version lastet

**Smartphone (please complete the following information):**

**Additional context**
fix it pls :) i hate socialilteproviders :)

**Comment by ItzKazuki** [comment]
if you want to check more deeply... please have a look https://dash.fikq-hosting.my.id/auth/callback
this is why the oauth is not working properly

**Comment by AVMG20** [comment]
you have most likely set it up incorrectly... if even discord is providing you with errors.
