### ISSUE TITLE
[feature] easy-to-read "time remaining"

### ISSUE THREAD

**Issue by 1day2die** [ControlPanel-gg/dashboard#196]
Pull-Request:
https://github.com/ControlPanel-gg/dashboard/pull/197

# 🚀 Feature Request

### Is your proposal related to a problem?
No

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

You have to do the Maths to calculate, how long your credits will last before your servers get suspended

### Describe the solution you'd like
A easy-to-read "time remaining" should be added next to your current Credit amount, how long the credits will last for.
For Example "You will run out of credits in x Hours /Days"

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

Nothing really...shouldnt be that hard i guess? and would be a nice feature :) 

**views/home.blade.php**

     `           <div class="col-12 col-sm-6 col-md-3">
                    <div class="info-box mb-3">
                        <span class="info-box-icon bg-success elevation-1"><i class="fas fa-hourglass-half"></i></span>

                        <div class="info-box-content">
                            <span class="info-box-text">Time left</span>
                            <span class="info-box-number">{{number_format(({{Auth::user()->Credits()}}/30)*$useage), 0, '.', '')}} <sup>days left</sup></span>
                        </div>
                        
                    </div>
                    
                </div>
                `

**Comment by anondev-sudo** [comment]
Really good idea, also users should see hourly and monthly cost of the specific server.

**Comment by 1day2die** [comment]
> Really good idea, also users should see hourly and monthly cost of the specific server.

https://github.com/ControlPanel-gg/dashboard/pull/198

Created a Pull-Request for this aswell

**Comment by 1day2die** [comment]
merged
