### ISSUE TITLE
[feature] Specific nodes for specific eggs

### ISSUE THREAD

**Issue by Xcyth** [ControlPanel-gg/dashboard#200]
# 🚀 Feature Request

### Is your proposal related to a problem?

It would be nice so if the admins can set specific eggs to be created on a specific node only. For example if a host owner wants to separate gaming and other eggs then they should be able to

### Describe the solution you'd like

Make a system so it checks what egg is allowed on what node and give the users the option to chose from the allowed nodes only

### Additional context

Nothing

**Comment by thewilloftheshadow** [comment]
This is already in the works, per the #sneak-peaks channel in the Discord server

![image](https://user-images.githubusercontent.com/35580099/134761565-52174658-7dbc-4264-aec8-e212493f4ed5.png)
