### ISSUE TITLE
Time remaining stuck on 1 hour left

### ISSUE THREAD

**Issue by ok236449** [ControlPanel-gg/dashboard#201]
**Describe the bug 🐛**
If you have a server that costs for example 0.1credits an hour,  when you run out of credits you may be left with 0-0.09 credits. That is not enough for the next hour, so the server gets suspended, but it will also get stuck at displaying 1hour left. (Cause the credits will never go to zero)

**To Reproduce**
1. Update to development version which contains the time remaining till credits run out.
2. Wait till you run out of credits and your server suspends

**Expected behavior**
Once servers get suspended, it should say 0 or "already ran out of credits" or something like that.

**Comment by 1day2die** [comment]
Fixed

**Comment by 1day2die** [comment]
https://github.com/ControlPanel-gg/dashboard/pull/210
