### ISSUE TITLE
Suspend user account

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#204]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

Recently our client purchased credits, but the payment has failed. The client got the credits added to the balance. 5 days after the purchase have received an email from PayPal that the payment was not successful.
![image](https://user-images.githubusercontent.com/85408287/134803671-b2758fd0-31c8-45da-811f-8a1c7f9010bd.png)
We asked the client to repeat the payment manually, and we have suspended their servers for the time we get it.
I got an idea that there should be an option to suspend a user account on the controlpanel.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Add button Suspend user to admin area on the user page. When a user is suspended, all their servers should be suspended automatically and when the user wants to access the controlpanel, an error message should be displayed like `Your account was suspended, please contact support for more information.`.  User should not be able to do anything on the dashboard, including purchasing credits and editing profile. Maybe when the user is suspended, the dashboard could automatically logout them and display an error message.

When a user is suspended, in the admin area there should be the button Unsuspend user, when you click on it, the user should be unsuspended and all their servers should be unsuspended too.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

**Comment by 1day2die** [comment]
PullRequest created
