### ISSUE TITLE
[feature] Arc.io added as a afk page for credit

### ISSUE THREAD

**Issue by GreenArrowlol** [ControlPanel-gg/dashboard#212]
# 🚀 Feature Request

### Is your proposal related to a problem?

*N/A*

### Describe the solution you'd like

N/A

(Describe your proposed solution here.)

### Feature Request

As theres arc.io you could probably add a page that gives credit per 60 mins of idle as its a pretty good feature and would be liked

(Write your answer here.)

**Comment by GeckoBoy84** [comment]
Will not happen as it against Arc's ToS

**Comment by 1day2die** [comment]
closed as it is really against the TOS
https://arc.io/faq#what-websites-can-use-arc
