### ISSUE TITLE
safe to ignore in the future?

### ISSUE THREAD

**Issue by finnie2006** [ControlPanel-gg/dashboard#215]
Package paypal/paypalhttp is abandoned, you should avoid using it. No replacemen                                                                                                             t was suggested.
Package paypal/rest-api-sdk-php is abandoned, you should avoid using it. No repl                                                                                                             acement was suggested.

**Comment by j122j** [comment]
https://stackoverflow.com/questions/67908412/php-composer-package-paypal-paypalhttp-is-abandoned
