### ISSUE TITLE
Allow username as login method

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#220]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

Users cant login with their username, they have to type their email each time.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Add that users can login with email or username. That username will be accepted too in the login field.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by anondev-sudo** [comment]
Any update on this? Users are annoyed that when they use google chrome auto generate password, the password is saved with username field instead of email field. And then when they want to login, google prefills the login to username not email. 

Controlpanel.gg should work same as ptero, that you can use email and username as login, not just email

**Comment by IceToast** [comment]
Will be implemented in v0.8

**Comment by 1day2die** [comment]
added
