### ISSUE TITLE
Once people run out of credits, delete servers and make from client to member

### ISSUE THREAD

**Issue by ok236449** [ControlPanel-gg/dashboard#224]
I have to toggle roles from client to member manually and also to warn people about the upcoming deletion.

### Describe the solution you'd like

I would like to automate this. For example, if someone runs out of credits and the server is suspended, on store its status is offline. There could be written something like "will be deleted in X days Y hours. Under it may be a button "make accessible for Z minutes, I want to download a backup and leave". (It would just unsuspend the server for a limited time,)
Otherwise, it could send an email notification to warn 5 days, 3 days, and 1 day before deletion.
After a user has no servers for a week, drop his role client back to member.
### Additional context
there may be an option in the configuration section to set the time before deletion (affects X, Y) and an option for the custom time (Z) to make it accessible for the backup download.

What is it all for?
1. The customer would deal with all those things himself.
2. It would be very clear in the user's list who is actively paying and who is interested no more.
3. Me and other hosts wouldn´t need to have an eye on every server when to message the owners of old servers to download data and delete it etc.

**Comment by ok236449** [comment]
This would also need to change the discord role assignment method, because so that it would remove the role on discord if it was removed on the dashboard and also give the role when it is given manually by admin, not only by purchasing. (Maybe just sync roles maybe every hour)

**Comment by snaildos** [comment]
+1 & bump

**Comment by GeckoBoy84** [comment]
We would not want to change them from client to member because they have still purchased credits which is what gives them the role.
