### ISSUE TITLE
Admin should be able to change password for other users

### ISSUE THREAD

**Issue by LogischJo** [ControlPanel-gg/dashboard#23]
# 🚀 Feature Request

### Is your proposal related to a problem?

If an admin wants to change an user password fast, it should be possible to edit it, like an admin can edit the user id.

### Describe the solution you'd like

Add an settings field for that to the user edit page: http://mydomain.com/admin/users/1/edit

**Comment by AVMG20** [comment]
yea that would be a nice addition :)

**Comment by LogischJo** [comment]
Done
