### ISSUE TITLE
Email doesn't sync with pterodactyl after updating

### ISSUE THREAD

**Issue by ayodev-in** [ControlPanel-gg/dashboard#231]
**Describe the bug 🐛**
When a user change its email it does not change on panel but changes on dashboard for some reason

**Comment by anondev-sudo** [comment]
I know that, also when you change password on dashboard it's not changed on panel.
I think that there should be config option to change email and password on pterodactyl too when it's changed on dashboard (or when password is reset on dashboard)

**Comment by BitSec01** [comment]
Should be possible with the Pterodactyl Api: https://dashflo.net/docs/api/pterodactyl/v1/#req_677bed2d8281425ab9e428fa6ed292e5

**Comment by anondev-sudo** [comment]
Yes you can update user on pterodactyl using API

**Comment by AVMG20** [comment]
Please, next time, make sure the title of the issue is more precise. This title is very confusing.

**Comment by 1day2die** [comment]
Will be fixed by https://github.com/ControlPanel-gg/dashboard/pull/348
