### ISSUE TITLE
Pterodactyl zero allocations found

### ISSUE THREAD

**Issue by AVMG20** [ControlPanel-gg/dashboard#24]
**Describe the bug 🐛**
if the user does not have any allocations it will throw an error but not the proper error :P 

![image](https://user-images.githubusercontent.com/45005889/121088926-b9e30300-c7e6-11eb-956a-80adf5f0d085.png)

**Comment by anondev-sudo** [comment]
There should be error popup thrown

**Comment by AVMG20** [comment]
i think i fixed it but i can't properly test this yet
