### ISSUE TITLE
[feature] Meta Controller and Upgrade notification

### ISSUE THREAD

**Issue by ZombieBro2044** [ControlPanel-gg/dashboard#242]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

Sometimes dashboard host owner's doesn't see new update announcement in controlpanel discord server and they don't update to latest version so just like pterodactyl you'll get version notification to update controlpanel dashboard to latest version if they want to and also meta controller page feature so dashboard comes better in google search results and also it will embeds links.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

(idk about upgrade notification but I saw meta controller page feature in one pterodactyl theme I have uploaded the file down, I know it won't help but you'll get clue what I mean. )

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(good luck)
![Image example](https://user-images.githubusercontent.com/77621560/138904775-1e962c8e-a832-4e06-a144-ae6aaa6a6384.jpg)

[Meta controller example](https://cdn.discordapp.com/attachments/862954747111538688/902571447782875216/MetaController.php)

**Comment by 1day2die** [comment]
both added
