### ISSUE TITLE
Out of credits in admin area show user and API

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#244]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

You will need to login as user to know when the user is out of credits

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Show out of credits in show user admin area and return it in /user/:id API too.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by GeckoBoy84** [comment]
Implemented
