### ISSUE TITLE
[feature] Resource/Server configuration overview / shop

### ISSUE THREAD

**Issue by IceToast** [ControlPanel-gg/dashboard#249]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

(Write your answer here.)
Users can't really see what a ressource configuration is build of (CPU, RAM ...)

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

(Describe your proposed solution here.)
I would like to see a overview (like a list of cards) of the available server configuration. Some general information about the configuration itself and a custom description text field that is more than just one line of text.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by anondev-sudo** [comment]
Maybe when you click on create server, plans should be shown like this. You should be able to add image and description to plans.

![image](https://user-images.githubusercontent.com/85408287/139807567-c3257479-3f56-410d-bf46-bab4031357a2.png)
When you click on order, display the form where you can write name, description, choose node, egg and create server

**Comment by 1day2die** [comment]
@LogischJo is working on that if im not mistaken

**Comment by 1day2die** [comment]
This is kinda changed in the current Dev Branch

![image](https://user-images.githubusercontent.com/8725848/140725333-8c0c5ac2-a704-41de-a73c-c6326af1b44c.png)


Feel free to re-open if this does not fit your needs :P
