### ISSUE TITLE
Custom useful links

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#25]
# 🚀 Feature Request

### Is your proposal related to a problem?
I can't change useful links without code modification 

### Describe the solution you'd like

Add that you can change useful links by rewriting database using phpmyadmin

### Additional context

*Is there anything else you can add about the proposal?

**Comment by anondev-sudo** [comment]
Yes, option to edit it and also option to add more messages

**Comment by LogischJo** [comment]
Ah i See…. Maybe an settings - Page in the Panel is better for it

**Comment by RamonRobben** [comment]
This can now be done using a command `php artisan create:usefullink` or with the phpMyAdmin database. Deleting still has to be done through the database. Might add a page for it later. Will be available when release comes out.

**Comment by anondev-sudo** [comment]
You should make same also for Links in navbar (Bome, Discord)
