### ISSUE TITLE
[feature] Information card at dashboard

### ISSUE THREAD

**Issue by IceToast** [ControlPanel-gg/dashboard#251]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

(Write your answer here.)

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

(Describe your proposed solution here.)
I want a information card where i can put general information or announcements on the dashboard of each user (like the useful links one)

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by GeckoBoy84** [comment]
Similar to #28
