### ISSUE TITLE
login page email-field is case-sensitive

### ISSUE THREAD

**Issue by IceToast** [ControlPanel-gg/dashboard#252]
**Describe the bug 🐛**
Logging in with an email containing an uppercase character will fail.

**To Reproduce**
1. Go to 'Login Page'
2. Login with your email but change a character to an uppercase character
3. See it fail lol

**Expected behavior**
Working login

**Comment by 1day2die** [comment]
could not reproduce.

**Comment by IceToast** [comment]
Sounds stupid, but yes... it is working... Maybe i got something wrong ^^
