### ISSUE TITLE
[feature] Verify discord acc with panel

### ISSUE THREAD

**Issue by matyasvane** [ControlPanel-gg/dashboard#257]
# 🚀 Feature Request

### Is your proposal related to a problem?

Verify a discord account with a panel.

(Write your answer here.)

### Describe the solution you'd like

The user would see their ID in the panel, for example: DoqPwi1

After typing the /verify DoqPwi1 command,
it would be checked that this ID exists, if so, the user will receive the @Verified group. 
If the player has a server, he would receive the @ServerOwner group
And if his account has administrator rights with the server somewhere, he would get an extra @ServerAdmin

Subsequently, a cron would run every 24 hours, which would gradually check all authenticated users, and if someone no longer had a server, the group would be removed.

The administrator could type / nickverify @discord_nick and see the username of the user he specified in the Pterodactyl registration.

### Additional context

This will allow better communication with the customer on the discord account. The administrator on the discord account will be sure that he is communicating with the user.

**Comment by j122j** [comment]
This looks more like a 3rd party addon, we don't want to add discord specific features such as slash commands. Also this is possible to make using the API and your own bot.
