### ISSUE TITLE
[feature] lock certain server configurations (shop) to a specific egg

### ISSUE THREAD

**Issue by IceToast** [ControlPanel-gg/dashboard#258]
# 🚀 Feature Request

### Describe the solution you'd like
I would like to have server configurations locked to a specific (or a selection of) egg(s).
For Example:
A configuration designed to handle MC Modpacks -> locked to a selection of Modpack Eggs
A configuration designed for Sourcemod Games -> locked ...  [Since Sourcemod Games usually take more space than minecraft servers]
etc...

**Comment by 1day2die** [comment]
![image](https://user-images.githubusercontent.com/8725848/139929316-5b2f2c5e-9e48-4a03-8a33-32d5c15ab1ef.png)


this is already WIP
