### ISSUE TITLE
OOM killer option

### ISSUE THREAD

**Issue by Hiekki4** [ControlPanel-gg/dashboard#266]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

Yes, as there is no option to enable oom killer on the product creation page, all servers are created with oom killer disable, and this makes me have to enable it manually

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

add a option on the product creation page to enable/disable oom_killer

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by 1day2die** [comment]
Apparently Pterodactyl-API has no option to enable the OOM-Killer

Re-open if im incorrect.
