### ISSUE TITLE
Dont display hours when you ran out of credits

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#269]
**Describe the bug 🐛**

**To Reproduce**
wait until you ran out of credits

![image](https://user-images.githubusercontent.com/85408287/140643477-48f27092-2df4-401d-af38-a8f606edb838.png)

**Expected behavior**

Remove hours and change icon to red colour.

**Additional context**

**Comment by anondev-sudo** [comment]
Notifications are spammy, send just one notification
![image](https://user-images.githubusercontent.com/85408287/140643493-973e21ea-f775-4f3a-84fa-59c35333b8e4.png)


Or atleast add option for users to delete them, mark as read/unread.

**Comment by 1day2die** [comment]
> Notifications are spammy, send just one notification ![image](https://user-images.githubusercontent.com/85408287/140643493-973e21ea-f775-4f3a-84fa-59c35333b8e4.png)
> 
> Or atleast add option for users to delete them, mark as read/unread.

This is a whole different issue and you already opened a issue for that. Please stop spamming
