### ISSUE TITLE
Hcaptcha support

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#27]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.

I can't use hcaptcha here.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
Add that you can choose if you want to use google recaptcha or hcaptcha.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by anondev-sudo** [comment]
And add google invisible recaptcha support

**Comment by GeekCornerGH** [comment]
And reCAPTCHA v3 support

**Comment by 1day2die** [comment]
we will only add recaptcha v3. no hcaptcha

**Comment by anondev-sudo** [comment]
But advantage of hcaptcha is that you can earn something on it

**Comment by Tix-Hosting** [comment]
> Ok add atleast that

I think you are using the Wrong Term with "Atleast" It sounds kinda disrespecting...

**Comment by anondev-sudo** [comment]
Sorry

**Comment by anondev-sudo** [comment]
Controlpanel should have option to use invisible reCAPTCHA as pterodactyl uses
