### ISSUE TITLE
Announcement system

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#28]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
I can't notify the users about some important message

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Add announcement system, that admins can set important message that will be displayed on every page of dashboard
### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by GeckoBoy84** [comment]
Similar to #251
