### ISSUE TITLE
When multiple locations are setup, some nodes can´t be used.

### ISSUE THREAD

**Issue by BolverBlitz** [ControlPanel-gg/dashboard#288]
**Describe the bug 🐛**
When there are multiple location in pterodactyl, only the nodes of the last location can be used to create new servers.

**To Reproduce**
Have 2+ locations with nodes
Try to create a new server on a node of the first location

**Expected behavior**
It should be possible to create a server on every linked node

**Screenshots**
![grafik](https://user-images.githubusercontent.com/35345288/141594298-a15db2d3-89f6-4f8a-9586-dc83a2a011eb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser Firefox 94

**Additional context**
Latest version 0.6 with product linking.

**Comment by AVMG20** [comment]
fixed
