### ISSUE TITLE
Add PayPal handling to invoices

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#290]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

It's confusing for users when I add some tax, I just want to set PayPal handling.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Add option to add item with custom name to invoice and to set custom price in % of that. This should be that you can set different % for different payment gateways.
I would create item with name Paypal handling.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by 1day2die** [comment]
most likely wont do that. just add this procentage to the tax, adjust your product prices or deal with the fees^^ <3

**Comment by anondev-sudo** [comment]
Yes I use tax for it already, but is it possible to rename Tax to Payment Gateway handling and to set different tax for stripe and paypal? Can you PR that?
