### ISSUE TITLE
Display server egg, nest, location, node and product name on the server's card.

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#294]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

User's don't know what plan are they using on the server, what egg they have there and so.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Display more details about the server like egg, nest, location, node and product name.

Also make that resources (RAM, CPU) will be displayed inside one table row. Should be similiar to card that is displayed when you are making new server.

![image](https://user-images.githubusercontent.com/85408287/141643144-eec00596-ee61-4aa7-ab00-6b5fdc5e8fdb.png)

Details about servers from pterodactyl should be fetched daily and cached. And then cached data should be used there. 
*This will also solve bug that when you rename server on pterodactyl, name is not updated on dashboard.*
And when you transfer the server to different node, or change egg, it would be updated after hour.
Cronjob should handle this. And also when server got removed from pterodactyl (404 status was returned), delete the server from database also on dashboard.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by 1day2die** [comment]
will be closed by 
https://github.com/ControlPanel-gg/dashboard/pull/315

**Comment by anondev-sudo** [comment]
This is meant on the servers pages. Not on servers create page

**Comment by anondev-sudo** [comment]
The PR does not fix this issue so unlink it

**Comment by 1day2die** [comment]
PR open
