### ISSUE TITLE
Server plans sorting

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#297]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

It's confusing for users that server plans are not sorted by price as before.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Sort it again by price. Or add option to setup custom sorting

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by William071802** [comment]
I would really like to be able to sort the plans ourselves. Right now it looks random

**Comment by 1day2die** [comment]
Fixed by this PR 
https://github.com/ControlPanel-gg/dashboard/pull/315

**Comment by IceToast** [comment]
> Fixed by this PR #315

It is not sorted yet. The new server selection is just another representation of the old selection, yet.

**Comment by anondev-sudo** [comment]
#294 is not implemented in this PR, this includes just redesign of server create page, servers page is not redesigned
