### ISSUE TITLE
[feature] Block useractions via configuration settings

### ISSUE THREAD

**Issue by BolverBlitz** [ControlPanel-gg/dashboard#299]
# 🚀 Feature Request

### Is your proposal related to a problem?
No

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

There is currently no good solution to prevent abuse, mentioned in #298 that dosn´t need manual work.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

There could be more settings in configuration like:
Prevent_New_Users - Disables the regestration
Prevent_New_Servers - Disables the generation of new servers
Prevent_Login - Disables login

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

If those settings are also avaible via the API, the admin can use already existing or self written programs that could stop such abuse.
If there are 200% more users that usual, a program could disable registration for some time or if someone spams a lot of servers or the nodes experience peak load a program could stop users from adding new servers.

**Comment by IceToast** [comment]
Done in #595
