### ISSUE TITLE
FraudLabs integration

### ISSUE THREAD

**Issue by Hiekki4** [ControlPanel-gg/dashboard#302]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

Make this dashboard more protected against fraud

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Make an integration with FraudLabs

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by IceToast** [comment]
Too complicated for now and all users need to accept that their data will be sent to just another service that you cant control
