### ISSUE TITLE
[feature]

### ISSUE THREAD

**Issue by Paulscr05** [ControlPanel-gg/dashboard#303]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

Paypal locks Accounts after Payment and you don't get the money directly after the Payment (you have to wait ~2 weeks)

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Add other Payment Methodes like Paysafecard and Stripe

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

No

**Comment by AVMG20** [comment]
duplicate
