### ISSUE TITLE
Add "Legal" Page

### ISSUE THREAD

**Issue by William071802** [ControlPanel-gg/dashboard#310]
# 🚀 Feature Request: Legal Page

Add a Legal page that we can customize with HTML. Add a link to this page to the top navigation bar. Would also be nice to be able to enable/disable this.

**Comment by anondev-sudo** [comment]
Yes and the link to this should be in the footer

**Comment by AVMG20** [comment]
we do wish on adding a way to make simple pages using an HTML editor. things like legal or cookie policy. or terms or what ever you feel like could be added here and added in the nav and or footer

**Comment by 1day2die** [comment]
basically added
