### ISSUE TITLE
[feature] Attach all nodes and eggs to all products.

### ISSUE THREAD

**Issue by OrefaSol** [ControlPanel-gg/dashboard#313]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

(Cannot attach all nodes and eggs to all products, therefore cannot create servers.)

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

(To be able to attach all nodes and eggs to all products.)

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Please fix it ASAP, my clients cannot create servers.)

**Comment by AVMG20** [comment]
(Cannot attach all nodes and eggs to all products, therefore cannot create servers.)
That's not how this works because you can't, for some reason, click a magic button that links everything to everything, which is very unusual behaviour. doesn't mean you can't link at all.
