### ISSUE TITLE
Automatic Invoice

### ISSUE THREAD

**Issue by BuildingDave** [ControlPanel-gg/dashboard#314]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

**In Germany (entire EU) it is mandatory to issue an invoice to a customer.
It would be great if you could integrate a possibility to generate automatic invoices. Also so that the customer can download them.

This would make your ControlPanel interesting for many in the EU.**

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

**Automatic creation of an invoice in PDF.
The following must be on it:
Name and address of the "company"
Individual invoice number.
Name and address of the customer.
What was bought.
Total amount.
Tax.

The customer should be able to download this invoice.
The hoster should be able to download ALL invoices for his bookkeeping.**

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

**If you have any questions, I'll be happy to help.**

**Comment by 1day2die** [comment]
This is basically done.
If anyone would like to test it, please let me know. It does need testing before it will be added to controlpanel

**Comment by 1day2die** [comment]
Will be merged in the next release
