### ISSUE TITLE
Buy Addon's Form Credits

### ISSUE THREAD

**Issue by IndionicHost** [ControlPanel-gg/dashboard#316]
# 🚀 Feature Request

I Think you should it will be good if you can buy Addon's like `Database`, `Backup`, `Allocation`, `CPU`, `Ram` Etc. Form Credits. Can Be Purchased on Hourly Base Or One Time Payment. When Server Get Deleted Addon Will Be Deleted Automatically

**Comment by IceToast** [comment]
Duplicate of #239
