### ISSUE TITLE
email problem

### ISSUE THREAD

**Issue by zsak1** [ControlPanel-gg/dashboard#319]
I have a problem

I got an e-mail that an account was created, but I did not receive a message after pressing verify e-mail

**Comment by zsak1** [comment]
![print](https://user-images.githubusercontent.com/25277653/144396513-f80ce685-25c4-48e1-9fb1-95d9b42c7223.png)
here is my email configuration

**Comment by 1day2die** [comment]
please edit this Issue and use the template provided

**Comment by zsak1** [comment]
already fixed
