### ISSUE TITLE
Check if server is not deleted, when running crontab to remove credits

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#32]
When running crotab job to remove credits, fetch server from pterodactyl api and save new information to database.
If server was suspended, don't remove credits.
If server was deleted (404 status), don't remove credits and delete server from dashboard

**Comment by AVMG20** [comment]
to many request, not worth it

**Comment by anondev-sudo** [comment]
So then how to cleanup the vps with backups and databases of deleted servers?

**Comment by anondev-sudo** [comment]
Ok, maybe there should be sync button in admin panel that will delete servers from dashboard that were removed from panel and update server names and descriptions.
