### ISSUE TITLE
[feature] Voucher links

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#323]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

That some users dont know where to type voucher code from giveaway and staff must tell it to them again and again.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Make voucher links, that when you go to `https://[APP_URL]/voucher/:code` it will automatically open redeem voucher popup with code pre-filled.

Also add link to the voucher url to code field in table so you can copy the link to the voucher. 
![image](https://user-images.githubusercontent.com/85408287/144625906-497c10e4-a2b1-4daa-b84d-1690087a92f5.png)

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by IceToast** [comment]
Gets closes by #363
