### ISSUE TITLE
When using the docker image, setting the host for mysql server does not affect migration

### ISSUE THREAD

**Issue by lewistham9x** [ControlPanel-gg/dashboard#324]
**Describe the bug 🐛**
When using the docker image, setting the host for mysql server does not affect migration. When running `php artisan migrate --seed --force`, I receive this error:   `SQLSTATE[HY000] [1045] Access denied for user 'dashboarduser'@'192.168.96.1' (using password: YES) (SQL: select * from information_schema.tables where table_schema = dashboard and table_name = migrations and table_type = 'BASE TABLE')`. The host is set to 192.168.1.182 within the .env file. What am I doing wrong?

**To Reproduce**
1. Go to .env
2. Set host to 192.168.1.182
3. Run the following as shown in the guide:
```
composer install
php artisan key:generate --force
php artisan storage:link
php artisan migrate --seed --force
```

**Expected behavior**
Mysql should be connected to the right ip

**Comment by 1day2die** [comment]
What the fuck are you Sure?

**Comment by lewistham9x** [comment]
It seems so, I'm going to try install without the docker image and will update you.

**Comment by lewistham9x** [comment]
Tried it on an entirely different host following the BUILDING.md steps with the same error, strange bug.
<img width="651" alt="image" src="https://user-images.githubusercontent.com/3887946/145659090-8875da49-7717-416e-bafe-113daedd3ff0.png">
<img width="574" alt="image" src="https://user-images.githubusercontent.com/3887946/145659116-6b5626c7-0df1-4b73-935c-48190f118fe4.png">

**Comment by lewistham9x** [comment]
Closing as I realised that I misinterpreted the error, the ip refers to the host I was connecting from and not to, and it was a typo in my .env file that caused the issue. Thanks for the help!
