### ISSUE TITLE
voucher Bug that takes credits away!

### ISSUE THREAD

**Issue by SneakyHub** [ControlPanel-gg/dashboard#325]
When a voucher is created if it has 1 use or a low amount of uses. If multiple people at the same time try and redeem it they'll be given a CRSF token error and whatever amount the voucher was for will be taken from the user.

Steps to reproduce.

1. make a voucher.
2. set its limit to 1 or a low amount
3. have a couple of people redeem it at the same time
4. bobs your uncle you made it to the bug! give yourself a pat on the back!

p,s found this out by giving away 250,000 credits and having people run into the CRSF token issue which yoinked a lot of their credits away!

**Comment by GeckoBoy84** [comment]
Unable to reproduce
