### ISSUE TITLE
Product section not returning in server details API call

### ISSUE THREAD

**Issue by Sneethan** [ControlPanel-gg/dashboard#326]
**Describe the bug 🐛**

When you make a call for server info, the product section is not returened. This means there is no way in the API to get server avaliable resources, or cost per month.
**To Reproduce**
Run the api call

**Expected behavior**
It returns everything except product
**Screenshots**
![image](https://user-images.githubusercontent.com/53156475/145703904-a32d9c3f-6090-4848-8700-d5b497cdf2d7.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BolverBlitz** [comment]
Add ?include=product to the end of your query. 
Like: {{url}}/api/servers/BPWT96Q1Bf0KNgk_jOmtp?include=product

**Comment by Sneethan** [comment]
Thanks, this worked

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by 1day2die** [comment]
So can this be closed?
