### ISSUE TITLE
Special characters in username

### ISSUE THREAD

**Issue by ok236449** [ControlPanel-gg/dashboard#337]
When a new user enters a username containing special characters (ěščřžýáíé) in the registration page, the system registers the user and deletes it shortly afterwards. This way the user does not know anything wrong happened (no errors visible), but cant login because the account does no longer exist. 

**To Reproduce**
1. Create a user with special characters. For example "é"

**Expected behavior**
normal registration

**Screenshots**
![image](https://user-images.githubusercontent.com/89067167/146977605-dd3a0396-67c8-4709-9ac1-c3813d17e244.png)

**Comment by 1day2die** [comment]
Hi,

are you sure that the username (username, email etc) does not already exist on pterodactyl panel?

If the email is already used on pterodactyl, this behaviour will appear

**Comment by ok236449** [comment]
> Hi,
> 
> are you sure that the username (username, email, etc) does not already exist on pterodactyl panel?
> 
> If the email is already used on pterodactyl, this behavior will appear

Yes, I spent about 5 minutes trying to understand what was happening and found out it was a special character. Other emails did not help, without the special character, it worked as normal.

**Comment by GeckoBoy84** [comment]
We have been unable to reproduce this, however please let us know if you are still encountering it.
