### ISSUE TITLE
Add-ons

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#34]
Add option to create add-ons and that users can choose them when creating server or any time when they need extra specs.
The add-on resources should be:
![image](https://user-images.githubusercontent.com/85408287/121210412-f14fbf00-c87b-11eb-8f0c-7946e69e83e8.png)
and when creating add-ons there should be form field for: name, description, resource type, amount of additional resource, monthly price in credits and products to which this add-on can be purchased

**Comment by RamonRobben** [comment]
We will not be adding this to the Dashboard as it exceeds the current scope of the project.

**Comment by anondev-sudo** [comment]
Ok, but will be product categories added as I have another parameters for bot hosting and for database hosting. And also that you choose which eggs and nodes can be used in that category

**Comment by RamonRobben** [comment]
@anondev-sudo I mean can't you make different server packages for different projects? bot hosting, database hosting etc?
The current billing is purely based on packages and not individual specs.

**Comment by anondev-sudo** [comment]
I will, when option to link eggs and nodes to products will be added.

And when https://github.com/ControlPanel-gg/dashboard/issues/171 will be implemented, it will solve my issue.
