### ISSUE TITLE
Does not send verification mail when using "POST  Create User"

### ISSUE THREAD

**Issue by BolverBlitz** [ControlPanel-gg/dashboard#345]
**Describe the bug 🐛**
No verification mail is send by cp.gg, only pterodactyl sends the welcome email.

**To Reproduce**
1: Use API to create new user

**Expected behavior**
I expect a verification mail to be send, yes a user can request one manualy but some of my users needed a bit of help because that process isn´t clearly showen on server creation page.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Debian 11 / Debian 10 / Ubuntu 20.04
 - Browser: Post Request is done using NodeJS Axios
 - Version Panel Version 0.6.2

**Additional context**
Either send E-Mail when new user registers via API or make it more obvius that he needs do to that manualy

**Comment by 1day2die** [comment]
Fixed by

https://github.com/ControlPanel-gg/dashboard/pull/346
