### ISSUE TITLE
[feature] Tax name

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#352]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

Some people as me use Tax to cover fees by payment gateways. Tax should be named handling in this case.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Add config option in admin area TAX_DISPLAY_NAME to set how tax should be named on invoices, on pdf invoices, on paypal/stripe checkout pages.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by IceToast** [comment]
This won't and can't be done correctly. We added stripe and PayPal taxes much differently. Taxes should be taxes. 

This issue is actually #351 and would Leader to a similar outcome.

**Comment by 1day2die** [comment]
https://github.com/ControlPanel-gg/dashboard/issues/351
