### ISSUE TITLE
Remove PAYPAL_EMAIL from env

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#353]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

I have noticed that PAYPAL_EMAIL in .env is useless. Its not passed to Paypal.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

https://github.com/ControlPanel-gg/dashboard/blob/development/resources/views/store/checkout.blade.php#L52
here replace the email on checkout page to `$InvoiceSettings->company_mail` (email that is set in invoice settings).

The data on checkout page should be the same as the data that are used for PDF invoice. If they are not, it may make users feel confused 😕.

Also instead of MAIL_FROM_NAME, company name should be used.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

Discussed with 1Day2Die

**Comment by 1day2die** [comment]
yeah this has to be refactored
