### ISSUE TITLE
flip around kredits usage namespaces

### ISSUE THREAD

**Issue by ok236449** [ControlPanel-gg/dashboard#355]
# 🚀 Feature Request

On the dashboard overview, there is a tile named "credits Usage" exactly. In other languages, it sounds exactly as bad (big U in the middle). I would suggest flipping the namespaces around like this:
{usage_of} {kredits_display_name}
this way, the credits display name is also in the same "Fall" and does not sound that bad. I don't know if it is better in German, but "credit Nutzung" does not sound good either.

**Comment by IceToast** [comment]
You mean that correct? 
![image](https://user-images.githubusercontent.com/54889359/147598265-0873bfed-346b-479c-8569-0cfe12cca598.png)

For the german translation what about "<credit_display_name> Bedarf"?

**Comment by ok236449** [comment]
Yes, that is better. In other languages, it is easier to translate it like this.

**Comment by IceToast** [comment]
Someone at discord suggested removing the credit_display_name entirely from this "card" and rename it to "Monthly costs". 
How bout that?

**Comment by ok236449** [comment]
U mean just something like "Total usage"? Not bad, why to solve a thing that can be avoided entirely. 😀
I'm a fan of that idea.

**Comment by 1day2die** [comment]
this seems to be fixed already?
