### ISSUE TITLE
per user usage + total credits usage

### ISSUE THREAD

**Issue by ok236449** [ControlPanel-gg/dashboard#358]
# 🚀 Feature Request
*This applies to the current developer branch

On/admin/users page, there is no longer per-user usage. I found that very useful in the past.
Also, in the admin overview, There is a tile saying total credits that have ever been in the system. If you gave credits to yourself for test servers, this value does not make any sense. However, I think current credits usage by non-admin users would be handier.

**Comment by LogischJo** [comment]
The per-user usage still exists on the Users show page. I believe it would be awesome if there is a settings for disabling admin user credits counting to the current usage.

**Comment by 1day2die** [comment]
fixed per usage on admins
