### ISSUE TITLE
[feature] Add user suspend/unsuspend to API

### ISSUE THREAD

**Issue by BolverBlitz** [ControlPanel-gg/dashboard#359]
# 🚀 Feature Request

### Is your proposal related to a problem?
- Yes

*Provide a clear and concise description of what the problem is.
- You currently can only (un)suspend a user via the users lists on controlpanel itself

### Describe the solution you'd like
- Add 2 new routs to the Users API.
 -PATCH: {{url}}/api/users/:UserID/suspend
 -PATCH: {{url}}/api/users/:UserID/unsuspend

**Comment by LogischJo** [comment]
I will work on a PR for this.

**Comment by 1day2die** [comment]
closed by
https://github.com/ControlPanel-gg/dashboard/pull/362
