### ISSUE TITLE
Payment system for clients

### ISSUE THREAD

**Issue by ok236449** [ControlPanel-gg/dashboard#360]
# 🚀 Feature Request

This is a giant piece of implementation. It will require a lot of work, time and effort, but it is a great thing.

1. There would need to be a second payment site just for clients.
2. Config site for clients. There they could set their name on receipt etc. There they could set up things that get sent into the console when somebody buys the thing. (just like you can set in pterodactyl "schedules" tab)
3. Some kind of API call, that would send the command to a server on pterodactyl.

**Comment by IceToast** [comment]
Im not sure i understand what you are suggesting.
Could you explain it more detailed?

**Comment by ok236449** [comment]
I mean an integrated VIP payment system. If a player purchases, something gets sent into the console via API and he gets a VIP rank ore something.

**Comment by 1day2die** [comment]
I suppose this is out of scope of this project

**Comment by ok236449** [comment]
I think it is not too far from the scope. Most hosting companies offer some kind of a VIP system

**Comment by IceToast** [comment]
For my taste its also way out of scope (at the moment). This would require a "huge implementation" as you just said.

**Comment by somerandomcloud** [comment]
This could be done even via a simple script... Depending where you want to add this VIP rank ofc. And you can calculate what purchases a user has made via maths, or by crossreferencing the servers they have and their balance to the store. No need to implement a new api endpoint and an integrated vip payment system. It is kinda out of scope for this project.

**Comment by IceToast** [comment]
> This could be done even via a simple script... Depending where you want to add this VIP rank ofc. And you can calculate what purchases a user has made via maths, or by crossreferencing the servers they have and their balance to the store. No need to implement a new api endpoint and an integrated vip payment system. It is kinda out of scope for this project.

That would assume there is some kind of interaction between "Panel Users" and "Clients" of that User. Running custom commands, maths etc etc. should be fairly easy. But the whole "Client" Payment interaction is completely new. Does a "Client" need to login to make a payment at that "Panel Users" Server? If so, where does he register - at the Panel, the Server?
If not, how would you keep track of the payments, invoices, userdata?

**Comment by SquidHost** [comment]
Add new payment systems such as Qiwi.com, FreeKassa.com. After all, they are very easy to install in any country and do not require complex manipulations.

**Comment by 1day2die** [comment]
Out of scope
