### ISSUE TITLE
Implementation of support ticket system in dashboard

### ISSUE THREAD

**Issue by firinggamers** [ControlPanel-gg/dashboard#365]
# 🚀 Feature Request

Implementation of support ticket system for enquiries etc for clients.

**Comment by anondev-sudo** [comment]
Really good idea, and in the ticket creation form there should be select to choose which server is the ticket regarding of

**Comment by 1day2die** [comment]
duplicate of
https://github.com/ControlPanel-gg/dashboard/issues/176

please use the provided format
