### ISSUE TITLE
Payment for all users

### ISSUE THREAD

**Issue by SquidHost** [ControlPanel-gg/dashboard#367]
Add new payment systems such as Qiwi.com, FreeKassa.com. After all, they are very easy to install in any country and do not require complex manipulations.

**Comment by IceToast** [comment]
1. Not using the feature request template
2. I cannot read a single word at the qiwi.com website as it does not feature a translation. But as far as i can tell it's just a company that provides you are bank card (in russia) with apple pay feature
3. FreeKassa.com seems not to be beneficial to this project as we already have two Payment providers to accept cards. We also accept googlepay, applepay and many others (via Stripe)

**Comment by SquidHost** [comment]
Qiwi - https://qiwi.business/en/ (For payments). STRIP IN RUSSIA IS NOT AVAILABLE!

**Comment by IceToast** [comment]
> 

Thanks for the info. I please you to not write in capslock. You did not say you are looking for a method available in russia tho.

**Comment by SquidHost** [comment]
I need methods in Russia and the same FreeKassa works in Russia and many countries. FreeKassa has a very easy site verification.

**Comment by IceToast** [comment]
reopened correctly by #390
