### ISSUE TITLE
[feature] Extra ports to a egg type.

### ISSUE THREAD

**Issue by Zoe8338** [ControlPanel-gg/dashboard#369]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

Yes, some servers such as unturned require more than one port allocated to them, therefor if there was a setting to auto alolocate an x amount of ports to a egg would be great!

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

When setting up a product, being able to choose a certain amount of extra ports to be allocated to that server type.

**Comment by GeckoBoy84** [comment]
Already Implemented
