### ISSUE TITLE
[feature] Lots of suggestions for update

### ISSUE THREAD

**Issue by SquidHost** [ControlPanel-gg/dashboard#385]
1. Add a ticket system for technical support, it's quite convenient.

2. Add filling in the last name, first name, patronymic during registration for security, so that the business is more calm.

3. I advise you to add a tariffs tab, where everything will be scheduled, I think it’s more convenient.

4. Add the function of payment by bank transfer, where bills will be automatically substituted on paper, this is in whmcs, it is very convenient.

5. Make editing the tariff or change it so as not to delete the server and recreate it.

6. Make a sale to the tariffs of additional services, for example, to buy ports, backups, databases.

7. And most importantly, the referral system is very convenient and receive % from purchases.

8. The function of auto-renewal of services if someone forgets to pay, the system will do it itself.

9. In the profile, add lines for adding passport data (confirmation of the client's identity), which is mainly required by many hosting.

10. Make your panel paid for at least 1-3 dollars a month, so together we will prevent the creation of fake hosting from schoolchildren who take tests from Google Cloud.

I hope that you will answer each item and say what you liked and what not.

**Comment by IceToast** [comment]
Please read other issues before you create on. Also please use the Issue template to create a feature request and request one feature at a time. It is really hard to keep track on all those suggestions at once.

1. Already requested #176 
2. In which way it would add security, except for invoicing? It is not legally required to have the full name to handle payments afaik
3. What is a "tariffs" tab?
4. Already requested and implemented by using stripe #259 
5. ???? No idea what you mean
6. Already requested #171 #239 #381
7. Please create a new feature-request for it
8. Subscriptions are possible by stripe without much effort now, please create a feature-request for it
9. Again you are not required to collect more personal data. Passport data is by far much out of the scope of security it's more about validation that a user has only one account 
10. This Project is open-source and will always be. It's a community project and its free to use. The problem about fake hostings and scams are known but there nothing we can do about it except making it closed source and using a paywall.

**Comment by SquidHost** [comment]
Yes, it's better to close the code and make the paid version of the scam it's scary.

**Comment by IceToast** [comment]
> .

No it's not. Its like saying you should make any software paid because it can get abused for scam. Thats just not how Open-Source works. As much is i would want to not have those scams/fake hostings built with cpgg, there is nothing we can do about it.

**Comment by SquidHost** [comment]
As an anti-fraud, you can check hostings by checking them, create a channel discord where verified hosts are listed on gg

**Comment by IceToast** [comment]
> As an anti-fraud, you can check hostings by checking them, create a channel discord where verified hosts are listed on gg

Sure we can, whos is gonna pay me or anyone checking the website, host, service, legally required documents in that country etc?

**Comment by SquidHost** [comment]
You can request the TIN of the hosts to verify them, and in order to get full verification they will have to pay you for confirmation and publication of the hosting in the discord channel.

**Comment by IceToast** [comment]
That would require firstly lots of work and secondly that we are a company with a location etc. No this is not gonna happen. 
This would not stop anyone from creating a scam host or anything like that. This will only help people who are interested in that project particular to see who could be trustworthy. It wouldn't help any customer that does not know about controlpanel and is not on our discord server -> the common customer you want to reach. 

It will be a never ending fight which we can't win. So no, we cannot and will not check what people do with this project.

**Comment by SquidHost** [comment]
Many fraudulent projects that already exist will appear (Russian)
