### ISSUE TITLE
Offer PayPal guest payments with credit card

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#39]
Hi, I think that you should setup PayPal guest payments with card. Some user don't want to create paypal account, with this they can pay with credit card without paypal account.

https://developer.paypal.com/docs/integration/direct/payments/guest-payments/

**Comment by anondev-sudo** [comment]
> With a Checkout custom-coded solution, there is an additional step: set SOLUTIONTYPE to Sole in your initial SetExpressCheckout API call.
If you use a third-party shopping cart, work with them or your developer to implement this variable.
As long as SOLUTIONTYPE=Sole is passed in the SetExpressCheckout API, Guest Checkout will be enabled.
For SOLUTIONTYPE=Sole to work, you must have PayPal Account Optional set to On within the PayPal account settings.
Many third-party carts provide an Enable Guest Checkout option in the Administration view of their Checkout module.

**Comment by anondev-sudo** [comment]
It is possible

**Comment by LogischJo** [comment]
Feel free to make an PR if you managed to implement it

**Comment by anondev-sudo** [comment]
I haven't changed code, just enabled in paypal account settings
