### ISSUE TITLE
[feature] FreeKassa payment module

### ISSUE THREAD

**Issue by SquidHost** [ControlPanel-gg/dashboard#390]
IceToast - love you...

I would like to add the FreeKassa payment module, which is very convenient and does not require business confirmation, it is registered for an individual or a company.

It has a lot of documentation in Russian, but I WILL TRANSLATE SPECIALLY FOR IceToast INTO ENGLISH TO BE BETTER.

https://freekassa.ru/ - website

https://docs.freekassa.ru/ - docs

In the documentation, almost all the code they wrote, they have many payment methods.

IceToast if you close this thread I'll rape you at home in your bed)) :love:

**Comment by GeckoBoy84** [comment]
We will not be adding payment gateways only used in Russia to the main repo over other more important features

**Comment by BOXmineYT** [comment]
What other payment system can you make if Stripe and PayPal They don’t work in Russia, so people ask for an alternative payment method, and in FreeKassa Not only payment in Russia and crypto currency.
