### ISSUE TITLE
Checkbox to remove Discord link (in top bar)

### ISSUE THREAD

**Issue by thierrybla** [ControlPanel-gg/dashboard#396]
I don't use Discord for my clients at all, however the link stays up there even when the Discord information is left empty.

It would be nice that if the Discord info is not filled in that the link does not display or that there is a checkbox to disable Discord entirely.
![image](https://user-images.githubusercontent.com/28044044/152975071-078008d1-2aea-434c-9be9-e36ccc31661e.png)

Thanks!

**Comment by IceToast** [comment]
Good suggestion!

**Comment by SneakyHub** [comment]
This is easily removed. It's basic html. 

Location:
/var/www/dashboard/resources/views/layouts/main.blade.php

Code Snippet:

            <li class="nav-item d-none d-sm-inline-block">
                <a href="{{env('DISCORD_INVITE_URL')}}" class="nav-link" target="__blank"><i
                        class="fab fa-discord mr-2"></i>{{__('Discord')}}</a>
            </li>


Just remove from <li class blah TO /li> (yes including the <>) then it'll be removed from your nav bar.

**Comment by thierrybla** [comment]
Of course but it's better to have it officially supported.

Updates also remove your HTML code.

**Comment by 1day2die** [comment]
Done
