### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#4]
Add that you can set your own useful links in db
Add that getting started notification message can be changed in db
Add google analytics support
Add that email and recaptcha keys are set on dashboard (like pterodactyl has)
Add option to create add-ons for plans and that users can choose them any time
Add option to upgrade your server to better plan
Add more server managment buttons for both admins and users (like reinstall, transfer, rename, set description, start stop kill buttons)
Add optional option that server description will be always server plan and egg and cannot be changed by user
Add custom pages support
Create voucher system (that admins create vouchers for some amount of credits, when user type correct vouchers, credits should be added, and vouchers should be for one-time use or more times usage and option to set voucher expiration)
Add support for more payment gateways
Add that you can set which nodes and eggs can be choosed for specific product
Add product categories and filtering by category
Create powerful support tickets system with email notifications
Option for admins to create new user, and option to link existing pterodactyl user with dashboard user when creating new user
Add email notification when server was suspended when you don't have enough credits
Simple email campaign (announcement) system
Add announcement system, that admins can set important message that will be displayed on every page of dashboard

**Comment by anondev-sudo** [comment]
Add hcaptcha support instead of google recaptcha

**Comment by anondev-sudo** [comment]
Display bar with text that please verify your email address when email is not verified to remind the user to verify the email

**Comment by anondev-sudo** [comment]
Include that default user with admin role is created automatically in docs + make docs for updating

**Comment by anondev-sudo** [comment]
When you have linked your account with discord, set user's first name to Discord user tag and last name to Discord user id. Better for admins to know who is who

**Comment by anondev-sudo** [comment]
Add setting minimum required credits to create server per product

**Comment by anondev-sudo** [comment]
When viewing user, add ptero link to that user

**Comment by anondev-sudo** [comment]
Rename Usage card to Monthly credits usage

And maybe there should be more billing stats, when on server page, there should be when it was purchased, option to change to another plan (product), last billed date (when credits were removed) and remind user before 7 days when the server will be suspended

**Comment by anondev-sudo** [comment]
After server is suspended, delete it within 14 days, when user did not purchased credits

**Comment by anondev-sudo** [comment]
Create more api endpoints, also for adding credits and suspending usera

**Comment by anondev-sudo** [comment]
Notify user when server was suspended in notifications and also send him an email.
And notify user 7 days before server will be suspended

**Comment by anondev-sudo** [comment]
Add that notifications (the bell icon) will be send also to email

**Comment by anondev-sudo** [comment]
I can't wait for more features.

**Comment by anondev-sudo** [comment]
When running crotab job to remove credits, fetch server from pterodactyl api and save new information to database.
If server was suspended, don't remove credits.
If server was deleted (404 status), don't remove credits and delete server from dashboard.

**Comment by RamonRobben** [comment]
@anondev-sudo Hello, thank you for all of your suggestions however to keep things nice and clean we would like you to use our new feature requests for submitting new feature requests. Each of your request can go into a new issue with proper description so that we can have a good overview of what you are requesting. This way we can also request more information about one specific feature and have a discussion about that as well as give them labels so we can prioritize them better. I will close the ticket but feel free to create new tickets for your features, I've seen some good ones in there.
