### ISSUE TITLE
Show actual server name 

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#400]
When you rename server on ptero, name is not updated on dashboard. It should be fetched and updated in database when admins click on Update in Overview page.

**Comment by IceToast** [comment]
Copy of what has been discussed in #170

**Comment by anondev-sudo** [comment]
Isnt the server fetched from ptero when there is node and location on the server card?

**Comment by IceToast** [comment]
Yes and that should be reworked anyways

**Comment by anondev-sudo** [comment]
So actual server name can be displayed on the card when it's fetched

**Comment by anondev-sudo** [comment]
So this can be reopened and #170 and be closed

**Comment by IceToast** [comment]
> So actual server name can be displayed on the card when it's fetched

No it needs to be reworked that there is no request to pterodactyl every single time you access the servers overview.

**Comment by anondev-sudo** [comment]
Yes, it should be cached. That max 1 request per day is made

**Comment by IceToast** [comment]
Already in progress from the #170 yes.
