### ISSUE TITLE
Monthly Based Billing

### ISSUE THREAD

**Issue by AussieDoggo** [ControlPanel-gg/dashboard#402]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

I am making a custom discord bot with a few friends and am planning to make customers pay 5 dollars/month to keep it running. Having it billed hourly will not be good for our company.  

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Adding the option on the admin section to allow for monthly credit billing per server. This will mean that we can bill it monthly and not make the prices so incredibly low and then have everyone complaining.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

No.

**Comment by IceToast** [comment]
This has been discussed hundreds of times. It's not going to happen as it does break the concept and is out of scope.
