### ISSUE TITLE
[feature] Referral code

### ISSUE THREAD

**Issue by partridge420x** [ControlPanel-gg/dashboard#417]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

- Having a referral system can be crucial for early development.
- Using a referral system gives incentives for people to recommend the service

### Describe the solution you'd like

Each customer will have an assigned "referral code" (auto generated, Possibly customizable (possibly even a signup redirect link with the referral code automatically entered)
When customers want to refer someone to use the hosting services, the customer would give someone their assigned code
When the referred person goes to sign up. It will ask for a referral code.
When entered it will give a customizable credit reward to the referrer and referee

Abuse prevention:

- assigned referral codes cannot be redeemed by the owner
- Possible VPN Prevention (nothing is perfect, but if its stopping the average joe, it helps)

(Describe your proposed solution here.)

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by EnderPace** [comment]
Yeah, a must to implement feature.

**Comment by 1day2die** [comment]
https://github.com/ControlPanel-gg/dashboard/issues/162

dupe
