### ISSUE TITLE
Peterdactyl Sync Bug Error 500

### ISSUE THREAD

**Issue by akashsardarop** [ControlPanel-gg/dashboard#418]
**Describe the bug 🐛**
When i click sync in overview to sync nodes with dashboard it shows error 500

Here are screenshot
![86D80819-41BE-49F1-9FD8-298205F8D29E](https://user-images.githubusercontent.com/73843791/158115042-109d0981-a1c7-4ac4-b2c5-1347638c8ccb.jpeg)
![49000CFE-B2FB-49B1-B040-FD0764F8C520](https://user-images.githubusercontent.com/73843791/158115079-bcc4d20a-c220-4b5a-89ed-78df6ab56c9e.jpeg)

**Comment by GeckoBoy84** [comment]
Works fine for everyone else. Ask for help in the discord server and we can assist you but this is not a bug but your configuration error.

**Comment by akashsardarop** [comment]
the link from email to verify account is also not working

**Comment by IceToast** [comment]
This is not an issue regarding the source-code. That issue is a result from missing steps at installation.
