### ISSUE TITLE
Store frontend

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#43]
Hi, I think that you should make some frontend for store (creating server and purchasing credits).
Maybe the products should be in cards

**Comment by RamonRobben** [comment]
@anondev-sudo Can you elaborate some more? Maybe show some wireframes.

**Comment by RamonRobben** [comment]
Can be re-opened when you submit more information like wireframes etc.

**Comment by anondev-sudo** [comment]
Make that products will be in card with product description and price in credits and purchase button.
When you click on purchase, then create server form with egg selection should appear.

https://i.ibb.co/Z2nWsbT/IMG-20210612-181357.jpg
