### ISSUE TITLE
Affiliate Program

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#44]
Make affiliate program, it should be optional if you want to turn it on.
There should be setting how much % of credit purchase you want to add to referrer of the user who purchased it. When you set it to 0, then it should be disabled.

When it is enabled in profile you should see your affiliate link (with your user id), when someone creates account on dashboard using this link, then referrer should be added to database. And when user who is purchasing credits were referred, they should get x % credits of credit purchase. It should be also logged to audit log.

**Comment by LogischJo** [comment]
Sounds nice

**Comment by 1day2die** [comment]
basically the same 

https://github.com/ControlPanel-gg/dashboard/issues/162
