### ISSUE TITLE
[feature] Payment, User, logging

### ISSUE THREAD

**Issue by MRJ-Badshah** [ControlPanel-gg/dashboard#444]
# 🚀 Feature Request

### Payment

1.Add new payment method like payment wallet , bank ,UPI, debit card.

### User

1.Add automatic user deletion after x days(config setting)
2.Don't allow user to create account after deleting account for x days(config setting)

### Logging

1.A logging system that can log activity in discord or any other platform.
Btw discord is main you can discord webhook

**Comment by IceToast** [comment]
Please create a feature request for each feature individual. Otherwise nobody can keep track.

1. Payment: Payment Wallet, Bank, Debit-Card is supported using Stripe

**Comment by MRJ-Badshah** [comment]
It's 

> Please create a feature request for each feature individual. Otherwise nobody can keep track.
> 
> 1. Payment: Payment Wallet, Bank, Debit-Card is supported using Stripe

Btw its Paytm wallet, there is a word mistake

**Comment by IceToast** [comment]
> 

Ah sure then, please create a individual issue for it :)

**Comment by RTK23-dev** [comment]
> # 🚀 Feature Request
> ### Payment
> 1.Add new payment method like payment wallet , bank ,UPI, debit card.


I am working on it and uh as soon I finish I can provide it to you or open a PR.

**Comment by 1day2die** [comment]
> > # 🚀 Feature Request
> > ### Payment
> > 1.Add new payment method like payment wallet , bank ,UPI, debit card.
> 
> I am working on it and uh as soon I finish I can provide it to you or open a PR.

PR or Ban!
