### ISSUE TITLE
Editing server slot products bug

### ISSUE THREAD

**Issue by LevM-A** [ControlPanel-gg/dashboard#446]
**Describe the bug 🐛**
When you created server slot product ( ![image](https://user-images.githubusercontent.com/59459622/173173829-4772d862-66db-40bb-90f7-103e4f51a59d.png) ) and when you edit the product the type of product is changing to credits and can not be changed to server slot.

**To Reproduce**
1. Go to 'Store'
2. Click on 'Create new'
3. Select Server slot type.
4. Create product.
5. Then edit the product 
![image](https://user-images.githubusercontent.com/59459622/173173935-cab43432-2eb3-43e2-846a-2ab3f1ed3a0c.png)
6. See that type of product changed and can not be changed to server slot. 
![image](https://user-images.githubusercontent.com/59459622/173173964-e10ffba2-4b91-428b-8fd2-38e8eddaa1bd.png)

**Expected behavior**
It will not change to credits and it will be available to change to server slot

**Screenshots**
![image](https://user-images.githubusercontent.com/59459622/173173918-20c7ddf6-fb13-4a8d-886a-109b2dbdedeb.png)
![image](https://user-images.githubusercontent.com/59459622/173173939-0996d246-f29d-47c6-8e41-0de8baf50f0c.png)
![image](https://user-images.githubusercontent.com/59459622/173173963-36b1c6e2-1e21-4386-a7a7-75d4ddb5039d.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Home]
 - Browser [Google Chrome]
 - Version [Version 102.0.5005.115 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**
 - Device: [None]
 - OS: [None]
 - Browser [None]
 - Version [None]

**Additional context**
None

**Comment by 1day2die** [comment]
You are very much correct. I forgot to do that. Will be updated on Monday.  Thanks for reporting!
