### ISSUE TITLE
Better error handling with the create user command 

### ISSUE THREAD

**Issue by LogischJo** [ControlPanel-gg/dashboard#45]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

Not detailed error handling in the Make user command 
### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Add better error messages 
### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

Please assign me to this issue

**Comment by AVMG20** [comment]
fixed
