### ISSUE TITLE
[Feature Request] Partner/Affiliate accounts with Automatic Payout Feature

### ISSUE THREAD

**Issue by Chronic-Reflexes** [ControlPanel-gg/dashboard#450]
# 🚀 Feature Request

(i would of made this sooner but thought the referral system may of touched up on it)

When working with entities like streamers, youtubers, Communities, etc. it would be optimal for a partner/affiliate program
The solution I have to this would be partner/affiliate accounts would be having separate affiliate/partner accounts

customers will be able to enter a partner code on credit checkout
![image](https://user-images.githubusercontent.com/26298829/173311051-462224b7-837a-44c3-b1fd-1f494f57382d.png)

Execution:

Partner signup:

- user would sign up for an account. like normal
- Manual account change (member) > (client) > (partner/affiliate)
- on first connect after account assign code if there is none (make customizable upon request)
- partner would be asked to input a PayPal email address for payment (with an: are you sure this is correct? (prompt)

Partner account:

- Partner would have an additional "wallet" on their account separate from normal functioning "Credit Wallet"
- "Credit Wallet" would keep its normal functionality and still be usable with the partner account
- "Partner Wallet's" contents will be shown in stores primary currency 
- When Customers use their Partner Code on checkout, configurable % of purchase gets put into "partner wallet"

Partner code creation:
- Choose % off first time credit purchase
- Choose % off Reoccurring Credit purchase (once member becomes client)
- Choose % going to partner off of first time credit purchase & reoccurring credit purchases using their partner code

Partner code redemption:
- would appear at checkout, roughly located by red square above.
- Enter partner code at checkout for customizable % off first time credit purchase if user is a member 
- Enter partner code at checkout for customizable % off reoccurring credit purchase if user is a client

Partner Payout:

-Partner will be able to request payout from "partner wallet" via button on "partner page":
  - configurable minimum/maximum for payout
  - configurable time between payout attempts
  - automatic/manual approval of payout
  - will only draw from "partner wallet"
  -upon manual/automatic approval, send payment to partner through assigned email address
  -if manually denying, ability to input why (200-ish characters max)
  

On top of the partner code, Partner could receive a personal voucher code to help fund services with us if they choose
  - would deposit credits in "credit wallet"
  - code would have 1 use, and renew monthly automatically
  - code would have customizable credit worth (already feature)
  
  
  (Advanced)
  
Partner levels: When a partner reaches configurable milestones. They "Level up" as a partner There would be a configurable amount of levels, with configurable requirements on reaching it

for instance:

Level 0/1 would be default, level 2 would require 5 purchases with your code to "level up", level 3 would require 15, level 4 would require 25, so on and so forth

When a partner "Levels Up" they would receive:
  - Increase in % received off of kickbacks
  - increase in "personal voucher code" value
  - Partner code would be a bigger discount per level (configurable)
  

Admin configuration/setup
admins will be able to create a default template that would apply to all partners, Or adjust each partner individually

(partner level page)

Panel would ask admin to create levels; Once level has been created
 you would click inside a level to expose more options
 
 Level 2
 - required purchases with partner code: 5
 - configure discount percent: 15%
 - configure partner kickback %: 15%
 - configure personal coupon code worth: 50 credits

 Level 3
  - required purchases with partner code: 5
 - configure discount percent: 20%
 - configure partner kickback %: 20%
 - configure personal coupon code worth: 70 credits

 Level 4
 - required purchases with partner code: 5
 - configure discount percent: 30%
 - configure partner kickback %: 30%
 - configure personal coupon code worth: 80 credits

(numbers and structure are just examples, but ideally would be done with dropdowns & small text boxes

**Comment by 1day2die** [comment]
i think this is done, no?
