### ISSUE TITLE
Show referred by

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#453]
Show who was the user referred by (in admin area, show user), also include there link to the referrer user.

Maybe users should also see who were they referred by in profile (but this should be optional).

**Comment by 1day2die** [comment]
![image](https://user-images.githubusercontent.com/8725848/173432041-95b5ec87-8ad2-4668-a296-0ed2d380bf19.png)


https://yourPanel.com/admin/users/<ID>

![image](https://user-images.githubusercontent.com/8725848/173432155-d0a6119c-f7aa-44ad-8a00-f096e8fbd25b.png)
 click the yellow button on the Users list

**Comment by anondev-sudo** [comment]
But I want to see who referred the current user I'm viewing (if someone did), it's annoying to browse all users to know who referred them.

**Comment by 1day2die** [comment]
done
