### ISSUE TITLE
Wrong payments sorting

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#454]
Data in payments table are not sorted correctly, the oldest payments are showed as first by default

![image](https://user-images.githubusercontent.com/85408287/173835955-a6200a53-76fd-40f8-87f8-6e9120c0bc2c.png)

Its in the code so idk why its sorted in bad order 
![image](https://user-images.githubusercontent.com/85408287/173836019-7618faa9-03af-4baa-a201-8c3e8516fcb2.png)

It should be sorted that latest payments are first to easier find the latest payments.

**Comment by IceToast** [comment]
That's not really an issue as the user can sort it themself (which gets saved in their browser). 
However i would love to see a PR from you to change the sorting order as described, because it does make sense!

**Comment by anondev-sudo** [comment]
Idk why it isn't working as it should

**Comment by IceToast** [comment]
> Idk why it isn't working as it should

It needs to be sorted descending not ascending.

**Comment by anondev-sudo** [comment]
Oh ok
