### ISSUE TITLE
[feature]  Regenerate a users Ref Link

### ISSUE THREAD

**Issue by Tix-Hosting** [ControlPanel-gg/dashboard#457]
# 🚀 Feature Request

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

An administrator should be able to regenerate a ref link for a user to prevent possible fraudulent activities

Regenerating the Ref ID also ensures that all users registered with this referrer are removed from the account and no more credits are assigned

**Comment by 1day2die** [comment]
why would it remove all reffered users i wonder?

**Comment by Tix-Hosting** [comment]
this is a reference to another issue regarding the permanent commission mode (Issue 459).  Here it makes sense after the regenerate to also prevent the users linked to the old ID for the commissions in the future.  Of course, this should not be removed from the admin view or something.

**Comment by Tix-Hosting** [comment]
What just came in my mind now: you could possibly also add to the feature that if an admin changes the Ref ID (both Random new ID (Issue #457) for Fraudulent Reasons and the CUCTOM ID(This Issue)), the user will receive a notification and/or an email  which alerts the user to this change.  


It would also be cool if changing the RefIDs is also possible via the API.  You don't need to differentiate between Custom REF ID and Regen ID here, since this is regulated by the own third party program.  Only one additional parameter would be very helpful, which indicates whether the refs should be deleted in the future for the new ref mode (Issue #459(Last comment has a further explaination) or not

I am writing this in the same Issue, as these Features are non Existent at the Moment and if i would create an Issue for a Feature based on another Feature which isn't yet Implemented, would be kinda confusing...
