### ISSUE TITLE
[feature] 

### ISSUE THREAD

**Issue by Kiku80** [ControlPanel-gg/dashboard#461]
# 🚀 Feature Request

 1.More payment gateway because RBI Dont allow indians to pay stripe and payapl create much more issue like it ask for verification more then 2 times in a month + take more then expected time to settle the amount.

 2.Monthly billing is really helpful for hosting specially for me 😅. If any developer is ready to help please contact me. ( i will pay )

**Comment by IceToast** [comment]
Please create a issue for each individual request and follow the template :)

Monthly billing might head into prod feel free to contact me on discord.
