### ISSUE TITLE
[feature]  List system

### ISSUE THREAD

**Issue by theh2so4** [ControlPanel-gg/dashboard#463]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

Yes, as I can't separate my products per list.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

In the admin panel, be able to put my products in a list, for example:

List: Minecraft
Products: Minecrafts hosting plans (S,M,XS,XL,XXL...)

Next list: NodeJs
Products: NodeJs hosting plans (S,M,XS,XL,XXL...)

And therefore this could be showed when an user creating a server, it will be better organized as the end user will be able to figure out easy what is actually happening.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

It will be very useful for separating the types of hosting that you could offer actually, and I don't it will take so much time to do it, it will be cool and useful if it gets added. :)

**Comment by 1day2die** [comment]
I don't know how that would improve the current system tbh. It seems quite similar? Am I missing something? :)

**Comment by theh2so4** [comment]
Nvm, I feel like an idiot right now
