### ISSUE TITLE
[feature] Buy whole node

### ISSUE THREAD

**Issue by theh2so4** [ControlPanel-gg/dashboard#464]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

It would ve very useful for people who actually need a whole node for their servers and manage their own resources from their own node.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Have the ability to buy a whole node por X coins each (month/week/day) if it's possible, and also have the ability from the admin side to select the eggs that the person who bought the node could deploy.

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

This would be a solution for persons who need bigger resources to plans that admins have setted up.

**Comment by DevMitchellZ** [comment]
So really, what you are wanting is to be able to purchase dedicated servers in essence ?

**Comment by Tix-Hosting** [comment]
> # 🚀 Feature Request
> 
> 
> 
> ### Is your proposal related to a problem?
> 
> 
> 
> *Provide a clear and concise description of what the problem is.
> 
> For example, "I can't change x and it makes me have to do manual work"*
> 
> 
> 
> It would ve very useful for people who actually need a whole node for their servers and manage their own resources from their own node.
> 
> 
> 
> ### Describe the solution you'd like
> 
> 
> 
> *Provide a clear and concise description of what you want to happen.
> 
> For Example, "Automate the changing of x so I don't have to do it manually"*
> 
> 
> 
> Have the ability to buy a whole node por X coins each (month/week/day) if it's possible, and also have the ability from the admin side to select the eggs that the person who bought the node could deploy.
> 
> 
> 
> ### Additional context
> 
> 
> 
> *Is there anything else you can add about the proposal?
> 
> You might want to link to related issues here, if you haven't already.*
> 
> 
> 
> This would be a solution for persons who need bigger resources to plans that admins have setted up.
> 
> 

Buy the "Server Splitter" Addon for Pterodactyl, make a Dummy Product with the Specs of the Node, select that the Product can only be Bought for this one Node, make this for every Node which you want to sell and then the Buyer has the Entire Node and can Split Resources in Multiple Servers as he Want. :)

I hope this helped you :)
