### ISSUE TITLE
[feature] Syncing already existing servers

### ISSUE THREAD

**Issue by sybetjeh** [ControlPanel-gg/dashboard#466]
# 🚀 Feature Request

### Is your proposal related to a problem?

Make cp.gg recognize already existing servers & add them to the correct user

### Describe the solution you'd like

The solution is to add some sort of button to sync already existing servers with cp.gg. this make it more mitigation friendly!
I didn't always use cp.gg and right now there are servers who aren't on the cp.gg panel, but just only on pterodactyl if yknow what I mean

**Comment by anondev-sudo** [comment]
I already made issue https://github.com/ControlPanel-gg/dashboard/issues/420

**Comment by anondev-sudo** [comment]
There is script for syncing users - https://market.controlpanel.gg/resources/resource/6-v07x--script-users-transfer/

**Comment by GeckoBoy84** [comment]
Duplicate of #170
