### ISSUE TITLE
Mailbox verification prompt: Multilingual processing is not set

### ISSUE THREAD

**Issue by Cjiio** [ControlPanel-gg/dashboard#467]
**Describe the bug 🐛**
Mailbox verification prompt: Multilingual processing is not set

**To Reproduce**
1. setting other languages in the background
2. Click to verify email
2. the returned prompt is in English

**Expected behavior**
Prompt for set language
In the web route, the mailbox verification message prompts that multilingual processing is not set

**Comment by 1day2die** [comment]
what are you tlaking about?
ANy Screenshots?

**Comment by GeckoBoy84** [comment]
No Response from user
