### ISSUE TITLE
[feature] arc.io passive earning

### ISSUE THREAD

**Issue by sybetjeh** [ControlPanel-gg/dashboard#468]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

No.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Make the feature passive income. This is on default disabled but can be enabled. You pass on your ARC ID (if you don't know what it is, google it yourself). You earn credits as long you keep the client page open. By arc.io you earn some revenue from it

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by 1day2die** [comment]
This has been discussed many times. It is against the TOS of arc and frowned upon by us. It will not be implemented by default
