### ISSUE TITLE
[feature]  Decimal Numbers

### ISSUE THREAD

**Issue by hoshic** [ControlPanel-gg/dashboard#472]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

It should be possible to use decimal numbers like 7.7, instead of rounding it up to 8 or down to 7. 
Example CH Tax is 7.7% so i you cant use 7.7% tax with the panel. Also it would be great if you could set non rounded values for product prices for some services so you could speak about euros instead of credits.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

That decimal numbers are possible. (Type=".01") - 0.01

**Comment by 1day2die** [comment]
added
