### ISSUE TITLE
New Payment Gateway [feature] 

### ISSUE THREAD

**Issue by Abraar69** [ControlPanel-gg/dashboard#477]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

I can't use Stripe in India

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

I would like to suggest PayU Payment Gateway for ControlPanel
https://www.payu.in/

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

Nothing additional, I'm hoping this Payment Gateway will arrive in the next update ;)

**Comment by GeckoBoy84** [comment]
We will not be adding payment gateways only used in India to the main repo over other more important features

**Comment by Abraar69** [comment]
> We will not be adding payment gateways only used in India to the main repo over other more important features

Alright
I would like to suggest Payoneer then, new payment gateway
https://www.payoneer.com/

**Comment by GeckoBoy84** [comment]
Please create a new github issue for that following the template
