### ISSUE TITLE
Annoying Referral Users Visual Bug

### ISSUE THREAD

**Issue by SneakyHub** [ControlPanel-gg/dashboard#483]
**Describe the bug 🐛**
Small but annoying. You go to the users tab in the admin area. I have 3,000+ users. I press the arrow going up to show who has the most referrals and it shuffles them but only shows my own referrals at the top and not all the other users.

**To Reproduce**
1. Go to controlpanel.domain.ltd/admin/users
2. Click on Referrals tab too list users with referrals lowest to highest.

**Expected behavior**
This should show me who has the most referrals at the top but sadly it doesn't.

**Desktop (please complete the following information):**
 - OS: Windows 10.
 - Browser Firefox
 - Version Latest

**Comment by 1day2die** [comment]
ill look into that^^

**Comment by 1day2die** [comment]
as a hotfix you can go to 
resources\views\admin\users\index.blade.php

on line 80 set "serverSide" to false.

This could increase loading times for you when checking the admin->user table by a tiny bit, but fixes the issue

**Comment by GeckoBoy84** [comment]
Implemented in v0.8
