### ISSUE TITLE
[Bug] GiroPay (Stripe)

### ISSUE THREAD

**Issue by snaildos** [ControlPanel-gg/dashboard#495]
**Describe the bug 🐛**
Enabling giropay forces you to use euros. Using any other currency causes it to SERVER ERROR. Maybe add a check if user is
paying with anything but USD, do not use "giropay" option.

**To Reproduce**
1. Add giropay in settings
2. Buy a USD product (fails)
3. Buy a EURO product (Works!)

**Expected behavior**
Some sort of checking method.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Additional context**
None

**Comment by AVMG20** [comment]
does not follow template

**Comment by snaildos** [comment]
issue can be re-opened.

**Comment by IceToast** [comment]
This check would need to take every single currency that is supported for any store product into account. However the user should check what is supported at their stripe account and currency imo.

When a payment method is not available to your account, should we check that too? If yes, thats pretty expensive to do. If no, why would we check against currencies when the user has to check if the currency is supported anyways?

**Comment by snaildos** [comment]
No, GiroPay only works with euro, so I expect the giropay argument to not be passed with any other currency except euro.

**Comment by IceToast** [comment]
Yes. This check does require to do what i described above as you can set different currencies for different products.

**Comment by snaildos** [comment]
> This check would need to take every single currency that is supported for any store product into account. However the user should check what is supported at their stripe account and currency imo.
> 
> When a payment method is not available to your account, should we check that too? If yes, thats pretty expensive to do. If no, why would we check against currencies when the user has to check if the currency is supported anyways?

"Why would we need to check against the currencies", well so I can use AUD and EURO on my store instead of forced to use EURO, else I get 504 errors.

**Comment by GeckoBoy84** [comment]
Or, you simply just disable giropay.

**Comment by snaildos** [comment]
> Or, you simply just disable giropay.

Then I need to manually turn it on and off when certain people want to pay.

**Comment by IceToast** [comment]
A rather simple solution would be to set a list of payment methods of stripe to each product indivudually. Because we cant nor shouldnt keep track of all payment methods stripe supports in general. We also cant and shouldnt keep track which method supports which country, because that can change. It shouldnt be our responsibility.

**Comment by IceToast** [comment]
Closed in favor for #577
