### ISSUE TITLE
Text overflow in server creation

### ISSUE THREAD

**Issue by jozefbonnar** [ControlPanel-gg/dashboard#500]
**Describe the bug 🐛**
When creating a server, the description of the server overflows outside of the box

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a product with a long description
2. Click on servers
3. Create a server
4. Then see the text-overflow

**Expected behaviour**
It should go down to the following line

**Screenshots**
![image](https://user-images.githubusercontent.com/42479938/182037901-b841224e-05f1-4aaa-ad5f-1670c591ff99.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 21H2 (Build 19044.1826)
 - Browser Brave (1.41.100 Chromium: 103.0.5060.134 (Official Build) (64-bit))

**Additional context**
Shouldn't the order be chronological with the price as well?

**Comment by 1day2die** [comment]
lol this is stupid.

To hotfix this, you can just press enter to make a linebreak on the description.

Also the Price order bug is fixed already in the next release :)

**Comment by jozefbonnar** [comment]
I should have looked at the code sooner then being lazy and doing the hot fix :disappointed:
