### ISSUE TITLE
[feature] Change how the tickets are sorted

### ISSUE THREAD

**Issue by sybetjeh** [ControlPanel-gg/dashboard#508]
# 🚀 Feature Request

### Is your proposal related to a problem?

The tickets are now sorted from the first ever ticket created to the newest one. If you get a bunch of tickets later, this will be a pain to navigate in.

(Write your answer here.)

### Describe the solution you'd like

I'd like the tickets to be shorted from newest, to oldest.

### Additional context

![image](https://user-images.githubusercontent.com/54631194/183520241-e94c3eef-da8e-473c-a7d5-46bf9958743a.png)

That's what I mean with the sorting^^. 

(Write your answer here.)

**Comment by 1day2die** [comment]
i added a new line @sybetjeh . please pull the newest version of the dev branch and check if the tickets are orders correctly

should be from newest to oldest

**Comment by sybetjeh** [comment]
yep, works! @1day2die
