### ISSUE TITLE
[bug] spam tickets

### ISSUE THREAD

**Issue by sybetjeh** [ControlPanel-gg/dashboard#512]
**Describe the bug 🐛**
https://cdn.bananahosting.xyz/7bb23b00 - auto-clicking the create ticket button. The number of tickets only shows like 10 of the tickets, but in reality, there are 100's of them if done properly/long enough.

https://cdn.bananahosting.xyz/abb277ca - The damage it actually has done.

I think you can even probably overload the DB with this if you automate it.

![image](https://user-images.githubusercontent.com/54631194/183855576-0e8863b7-1638-4fc2-94e9-5b0129ec7b0f.png)
It still continues to create tickets even after stopping auto-clicking it, I assume it's still catching up? I can't confirm this though

**To Reproduce**
1. Be on dev branch
2. Go to the create a ticket page
3. Download an auto clicker or just click it yourself rapidly
4. See the damage it has done

**Expected behavior**
The system should temporarily rate-limit you for creating so many tickets in a short amount of time. You could also just limit the open tickets you can create altogether (e.g 2).

**Screenshots**
look at describe the bug

**Desktop (please complete the following information):**
Irrelevant

**Smartphone (please complete the following information):**
Irrelevant
**Additional context**
N/A

**Comment by sybetjeh** [comment]
Went into phpmyadmin, this is the actual number of amount of tickets it created in a span of 30 seconds or so.

![image](https://user-images.githubusercontent.com/54631194/183856829-bbb5b9c2-afe1-46a6-981f-35197b77e722.png)

**Comment by 1day2die** [comment]
aaah very good!

**Comment by sybetjeh** [comment]
![image](https://user-images.githubusercontent.com/54631194/183867064-573b7796-f54d-41e8-a0e9-86b52c3dc79a.png)
also don't forget to add the delay or whatever you wanna call it on the api itself too

**Comment by sybetjeh** [comment]
Additional: There's also no cooldown for how many comments you can post. You can post 100's of them in 1 ticket without having a single issue, until your site gives up
