### ISSUE TITLE
[feature] add a button to blacklist certain people from making tickets

### ISSUE THREAD

**Issue by sybetjeh** [ControlPanel-gg/dashboard#518]
# 🚀 Feature Request

### Is your proposal related to a problem?

If you have people who abuse your ticket system, there's no way to restrict them from using it. 

(Write your answer here.)

### Describe the solution you'd like

Make a button that "blacklists" them from making tickets

(Describe your proposed solution here.)

### Additional context

no

(Write your answer here.)

**Comment by 1day2die** [comment]
you could also just suspend their accounts lol.

Are there really people who abuse this kinda stuff?

**Comment by sybetjeh** [comment]
> you could also just suspend their accounts lol.
> 
> Are there really people who abuse this kinda stuff?

no because that'd also remove their servers if they got one. And yes, I have got people abusing it
