### ISSUE TITLE
[feature] Gmail +(1) trick

### ISSUE THREAD

**Issue by sybetjeh** [ControlPanel-gg/dashboard#533]
# 🚀 Feature Request

### Is your proposal related to a problem?

I have people using the + trick on their gmail account to make multiple accounts on the same gmail address.

(Write your answer here.)

### Describe the solution you'd like

Make a tab where admins can ban specific characters (or words) from being used on an email address. Or you can build "malicious" (like +) characters in CP itself

(Describe your proposed solution here.)

### Additional context

n/a
(Write your answer here.)

**Comment by Tix-Hosting** [comment]
Just enable the IP check in your admin settings 😀

**Comment by sybetjeh** [comment]
> Just enable the IP check in your admin settings 😀

That's easily bypassable, not a solution

**Comment by sybetjeh** [comment]
I also have that enabled.

**Comment by GeekCornerGH** [comment]
Twitter also allows + trick, so idk if it is vital
