### ISSUE TITLE
[feature] internal ticket function buttons. 

### ISSUE THREAD

**Issue by kenshin133** [ControlPanel-gg/dashboard#554]
# 🚀 Feature Request

### problem 

We have buttons to delete, close on the ticket overview section but I think we should have them inside the ticket also for quicker management. 

### Describe the solution you'd like

1. I think we Should add buttons close to the submit reply button to be able to close, tag, or re-prioritize tickets. 
2. Additionally perhaps more tags like "waiting for client info" or "pending fix" may be helpful when more tickets are being handled.

**Comment by GeckoBoy84** [comment]
Please use the format next time
