### ISSUE TITLE
[feature] add image support to tickets

### ISSUE THREAD

**Issue by sybetjeh** [ControlPanel-gg/dashboard#558]
# 🚀 Feature Request

### Is your proposal related to a problem?

n/a

(Write your answer here.)

### Describe the solution you'd like

let us upload images in ticket, but delete them off the server after a certain days to avoid filling disk space or sum

(Describe your proposed solution here.)

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by AGuyNamedJens** [comment]
Wouldn't it be better to allow to post images like github allows you to?

Like ![This example](https://images.app.goo.gl/6KsNLzu8FwyPPoD16)?
Images can be really stressful for servers, especially if a person abuses tickets in my thoughts.

**Comment by sybetjeh** [comment]
yeah you can do that, but my servers can handle quite a bit of stress - so uploading it directly on mine would be no problem in my case

**Comment by 1day2die** [comment]
wont be implemented. Imgur will be a suitable solution for this.
