### ISSUE TITLE
Users table sorting is buggy

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#563]
**Describe the bug 🐛**
The sorting of users in the users table by last seen doesnt work as expected.

**To Reproduce**

Go to dashboard and click users.

**Expected behavior**
Sort it by last seen date

**Screenshots**
![image](https://user-images.githubusercontent.com/85408287/185111879-07a5234b-cc63-4a53-8759-b3bf018e9fd2.png)

**Additional context**

**Comment by GeckoBoy84** [comment]
Fixed in newest release
