### ISSUE TITLE
[feature] Dashboard Read Node Overallocation 

### ISSUE THREAD

**Issue by EpicLifeYT12** [ControlPanel-gg/dashboard#576]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

(NoN)

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

(If pterodactyl node set overallocation, the panel will read that number instead of the default

E.g: if the node set to 5gb max RAM: but its overallocate to 10GB, 

Panel read 10GB instead of 5GB)

**Comment by ok236449** [comment]
Already fixed in dev branch
