### ISSUE TITLE
Recaptcha on Password Reset Request Page to prevent abuses and botting

### ISSUE THREAD

**Issue by r-kjha** [ControlPanel-gg/dashboard#580]
# 🚀 Feature Request

### Is your proposal related to a problem?

It would be really great if you could implement the Recaptcha on the password reset request page like same as in register and login page. This will prevent abuses and botting.

![image](https://user-images.githubusercontent.com/87710356/195970388-85db28fe-e597-49e9-a4c8-6713e222574a.png)

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Add Recaptcha on password reset request page

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

No, thank you.

**Comment by AGuyNamedJens** [comment]
We'll implement this into V1.0

**Comment by 1day2die** [comment]
fixed in newest release
