### ISSUE TITLE
Exclusion of users via API.

### ISSUE THREAD

**Issue by Ferks-FK** [ControlPanel-gg/dashboard#585]
**Describe the bug 🐛**
For some reason you can delete a user that has servers associated with it in CPPG/Pterodactyl.
This can be dangerous, because everything gets deleted, even though we have servers associated with the user.

**To Reproduce**
1. Create one user.
2. Create a server for it via CPGG.
3. Delete the user via API.
4. See the user and all his servers being deleted.

**Expected behavior**
Generate an exception saying that you cannot delete users that have servers associated with them.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome
 - Version 106.0.5249.119

**Additional context**
When this happens, apparently the user is deleted from the CPGG, but remains in pterodactyl.
This can also lead to ghost users.

**Comment by 1day2die** [comment]
What. This is no Bug. It's intentional. Why would you delete a user but wouldn't delete his servers? Who would be the new ownrr of the servers?

Its intentional that everything related to the user will also get deleted when the user gets deleted

**Comment by Ferks-FK** [comment]
> What. This is no Bug. It's intentional. Why would you delete a user but wouldn't delete his servers? Who would be the new ownrr of the servers?
> 
> Its intentional that everything related to the user will also get deleted when the user gets deleted

and I am not mistaken, in ptero this does not happen.

**Comment by 1day2die** [comment]
Ah the user should obviously be deleted on ptero though.....

Okay.
