### ISSUE TITLE
[feature] Option to block certain email providers from registering on the website

### ISSUE THREAD

**Issue by SneakyHub** [ControlPanel-gg/dashboard#590]
Hey! So after a year and a half of using this controlpanel. I have noticed that there are plenty of users attempting to abuse the system by making multiple accounts and signing up using spam email providers to attempt to either claim the referral bonus, make bot accounts, make bad servers that are used to abuse the host in some way or to bypass our systems in some way. Spam email providers are a massive pain in the ass and to discourage that sort of behaviour I'd like to start blocking certain email providers.

I would love for there to be an option for us hosts to block certain email providers at some point. This isn't a priority but would be a create feature to have!

**Comment by sybetjeh** [comment]
Perhaps follow the template that is given to you when requesting a new feature, this makes your message more organized.

**Comment by GeckoBoy84** [comment]
Does not follow the template
