### ISSUE TITLE
500 error when click overview tab

### ISSUE THREAD

**Issue by Mrfixit935** [ControlPanel-gg/dashboard#596]
**Describe the bug 🐛**

**To Reproduce**
1. Go to 'admin page'
2. Click on 'Overview'
4. See error: 500 error

**Expected behavior**
Takes me to the overview tab
**Screenshots**
![739a80dc631e5d18ba7e7e773286bda1](https://user-images.githubusercontent.com/61997640/200209784-5cb86fb0-204f-4a95-8af0-f0b290727360.png

**Desktop (please complete the following information):**
 - OS:Windows 
 - Browser Firefox
 - Version idk

**Smartphone (please complete the following information):**

**Additional context**
logs: https://pteropaste.com/i5d0f9

**Comment by SahrulGnwn** [comment]
can you enable debugging in `.env` then reproduce the error back to know what caused it

**Comment by GeckoBoy84** [comment]
Not a bug.
Please join our discord server and ask for help there.
