### ISSUE TITLE
[feature] 

### ISSUE THREAD

**Issue by TheAmazonGuy** [ControlPanel-gg/dashboard#597]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

People can make new accounts with VPN

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

make a anti vpn system

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

no

**Comment by GeckoBoy84** [comment]
You haven’t even put a title???

**Comment by 1day2die** [comment]
This is something you cannot tackle. People will always find a way to abuse free credits System.
