### ISSUE TITLE
Email system not working

### ISSUE THREAD

**Issue by TheAmazonGuy** [ControlPanel-gg/dashboard#598]
**Describe the bug 🐛**
Email sys not working

**To Reproduce**
1. Go to Users
2. Click on Notify 
3. send a email to a user

**Expected behavior**
It will send email

**Screenshots**
its just says " 500 Server error"

**Desktop (please complete the following information):**
 - Browser Firefox 

**Additional context**
Logs https://pteropaste.com/g2evjt

**Comment by GeckoBoy84** [comment]
You have not setup emails correctly. None of your issues are bugs just your misconfiguration. Ask for help in the discord.
