### ISSUE TITLE
Server owner transfer system

### ISSUE THREAD

**Issue by playaz44** [ControlPanel-gg/dashboard#600]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

Currently when changing the owner of the server in Pterodactyl, there is a need in CPGG manually change the owner of the server in the SQL database.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

I would like to propose a server owner transfer system on the CPGG side + synchronization in pterodactyl

**Comment by IceToast** [comment]
This should only be on the admin site as i would understand your request, am i right?

**Comment by IceToast** [comment]
Added in #636
