### ISSUE TITLE
money is not debited with payment by the hour

### ISSUE THREAD

**Issue by Aspect095** [ControlPanel-gg/dashboard#602]
**Describe the bug 🐛**
If you order a server for payment by the hour your money will write off only for the first hour.

**ToReproduce**
1. Go to 'servers'
2. Click on 'create server'
3. After creating 'wait 1 hour'
4. See your balance (it will stay the same)

**Expected behavior**
I've tested the dashboard and found this error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [chrome]
 - Version [latest]

**Smartphone (please complete the following information):**
 - Device: [Poco M5]
 - OS: [MIUI 13]
 - Browser [chrome]
 - Version [latest]

**Comment by GeckoBoy84** [comment]
Not a bug - you haven’t configured your cron job. Read the docs or ask for help in our discord server.
