### ISSUE TITLE
Economy bug report! 

### ISSUE THREAD

**Issue by SneakyHub** [ControlPanel-gg/dashboard#603]
**Describe the bug 🐛**
Have one account. The host must have verification rewards. Example 10 credits if they verify their email or discord account.

**To Reproduce**
1. Create an account
2. Navigate over to the profile page.
3. Verify your discord account or email.
4. The system will auto give you the credits.
5. Unsync your discord account and sync another discord account too it.
6. You can also do this with another email address as far as I am aware.
7. Then the process starts repeating itself as soon as you verify and unverify then verify again the system will continue to reward you over and over with no limit. The user can create an autohotkey or another macro to repeat this process infinityly.

**Expected behavior**
Reward is only supposed to be given once per verification method.

**Screenshots**
No screenshots for this since it's very simple to reproduce from the steps above.

**Desktop (please complete the following information):**
 - Tested on a windows 10 64 bit machine using firefox.

**Smartphone (please complete the following information):**
 - was not tested on mobile.

**Additional context**
This is running the latest version of controlpanel.gg. This currently affects all versions of the software.

**Comment by SneakyHub** [comment]
This issue is confirmed some lemon at controlpanel decided to close this issue like it's no big deal.

[
![image](https://user-images.githubusercontent.com/78713939/208261630-aac74199-4e56-4036-bc13-ffa2acce430d.png)
](url)

**Comment by lylawatts** [comment]
Childish admin ;p
