### ISSUE TITLE
Payoneer Payment Gateway [feature] 

### ISSUE THREAD

**Issue by QuikBolte** [ControlPanel-gg/dashboard#604]
# 🚀 Feature Request

### Is your proposal related to a problem?

Please add Payoneer Payment Gateway, it's required for us and only option that works.

(Write your answer here.)

### Describe the solution you'd like

Payoneer Payment Gateway like others in CP.gg i.e PayPal and Stripe.

**Comment by GeckoBoy84** [comment]
Duplicate Suggestion #497
