### ISSUE TITLE
[feature] Making a manual docs instead of having automated docs

### ISSUE THREAD

**Issue by BeastBoyADI** [ControlPanel-gg/dashboard#607]
# 🚀 Feature Request

### Is your proposal related to a problem?
Yes

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

(Write your answer here.)
So the problem is some automated docs are wrong as when i followed that it was return errors even if we follow the exact same method as per the docs. Like i discussed in the support server.

### Describe the solution you'd like
*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

(Describe your proposed solution here.)
The solution would be making a markdown documentation which will be pull requested by users and collaborators after verifying will pull them. In that way all types of users will help you make a perfect documentation as well as the docs will be accurate.
### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

(Write your answer here.)

**Comment by 1day2die** [comment]
what

**Comment by IceToast** [comment]
>The solution would be making a markdown documentation which will be pull requested by users and collaborators after verifying will pull them. In that way all types of users will help you make a perfect documentation as well as the docs will be accurate.

That's how the docs atm work actually.
Have a look at https://github.com/ControlPanel-gg/docs/tree/main/docs.

**Comment by BeastBoyADI** [comment]
> > The solution would be making a markdown documentation which will be pull requested by users and collaborators after verifying will pull them. In that way all types of users will help you make a perfect documentation as well as the docs will be accurate.
> 
> That's how the docs atm work actually. Have a look at https://github.com/ControlPanel-gg/docs/tree/main/docs.

Oops it's my bad. i forgot to mention that this request is for the API documentation which is atm automated
