### ISSUE TITLE
Dashboard User registrieren

### ISSUE THREAD

**Issue by TylerSchoen14** [ControlPanel-gg/dashboard#610]
Wenn sich ein User im Dashboard registrieren möchte, wird es nicht im Dashboard registriert sondern nur im Panel. Dashboard würde wie nach Docs installiert. Was tun?

**Comment by 1day2die** [comment]
Hi. Am besten kommst du mal in unseren discord in den Support channel

**Comment by 1day2die** [comment]
https://discord.gg/4Y6HjD2uyU
