### ISSUE TITLE
Eggs and nests description

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#62]
I think that users should see eggs description in () when choosing egg and nests description too.

**Comment by AVMG20** [comment]
what happens if the egg description is an entire wall of text? and you offer like 4 eggs from 1 egg having this?
this won't really work inside a select option

**Comment by anondev-sudo** [comment]
Maybe make that when you put mouse on specific select, tooltip with egg/nest description will be shown (if any)
