### ISSUE TITLE
Option to mark eggs as disabled

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#66]
There should be that when you click on nest, there you can disable eggs that you don't want to use.

Better alternative:
Add product categories and that you can choose which eggs and nodes can be used for that category when creating servers.
When you don't choose that egg in any category, then it can't be choosed (will be disabled).

**Comment by AVMG20** [comment]
your alternative has nothing to do with disabling eggs

**Comment by 1day2die** [comment]
This should basically be fixed in the current dev branch if im not confusing something here?
Closing the issue. Feel free to re-open if needed
