### ISSUE TITLE
[Bug] Referral-Code not created on  make:user command

### ISSUE THREAD

**Issue by GeckoBoy84** [ControlPanel-gg/dashboard#665]
**Describe the bug 🐛**
Referral Code is required on edit user, it should not be!

**To Reproduce**
1. Go to users
2. Click on edit
3. Try and save
4. See error if the user did not use a referral code

**Screenshots**
![image](https://user-images.githubusercontent.com/67899387/215345127-7cfd8036-e54c-4160-a4c9-974ef112f6da.png)

**Comment by 1day2die** [comment]
this really isnt high priority. It should be this way.

Every user needs a referal code and every user gets created with a random referral code. 

Even if the hoster dosent want the referral enabled at first, what if he decides to enable it a few months later and users dont got a code?

**Comment by GeckoBoy84** [comment]
In that case, there needs to be a way to generate a random referral code for every user created before the feature was released.

**Comment by IceToast** [comment]
Why isnt it created in the first place? 
When this feature got implemented -> it should generate a ref-code for every user on updating

**Comment by GeckoBoy84** [comment]
Thinking about it, the user that I was editing was actually created on the latest update, not before

**Comment by 1day2die** [comment]
every user who was created before the update gets a random referral code

**Comment by GeckoBoy84** [comment]
Yeah just checked, that works however that user did not have a referral code created

**Comment by 1day2die** [comment]
![image](https://user-images.githubusercontent.com/8725848/215352033-23282b1e-63f0-4e18-94a0-d462a7d7098a.png)


maybe some weird edge case?

**Comment by GeckoBoy84** [comment]
Existing users have a referral code, but that user doesnt - perhaps its because it was created with the artisan make user command?
I originally thought the setting was the referral code that users signed up with rather than their own referral code

**Comment by 1day2die** [comment]
>  perhaps its because it was created with the artisan make user command?

Very important info there. Yup. Referral code isnt on the make user command

**Comment by GeckoBoy84** [comment]
Its hard to remember what you did 😅

**Comment by 1day2die** [comment]
https://github.com/ControlPanel-gg/dashboard/pull/668
