### ISSUE TITLE
[feature] Add display column to /admin/payments

### ISSUE THREAD

**Issue by GeckoBoy84** [ControlPanel-gg/dashboard#677]
# 🚀 Feature Request

### Is your proposal related to a problem?
Impossible to know whether a user purchased credits or server slots etc if prices are the same

### Describe the solution you'd like

Add "Display" to /admin/payments so you can see what package was bought (ie if you have 2 packages of same price)

**Comment by 1day2die** [comment]
![image](https://user-images.githubusercontent.com/8725848/215717511-b335057b-3168-4d2a-aa0c-6eac30179ec1.png)
?

**Comment by GeckoBoy84** [comment]
But does not show exactly what package, if you run special offers etc
