### ISSUE TITLE
Referral system info buttons auto closing

### ISSUE THREAD

**Issue by GeckoBoy84** [ControlPanel-gg/dashboard#682]
**Describe the bug 🐛**
Referral system settings - always give commission info button and allowed info button auto close on mobile

**To Reproduce**
1. Go to to referral system settings on mobile
2. Click on the info buttons
3. See error

**Expected behavior**
They don't auto close

**Comment by 1day2die** [comment]
cant reproduce

**Comment by GeckoBoy84** [comment]
Reproducible

**Comment by GeckoBoy84** [comment]
Determined it is iOS but not android (sample size of 2)

**Comment by IceToast** [comment]
Duplicate #683
