### ISSUE TITLE
Issue with adding new partners

### ISSUE THREAD

**Issue by SneakyHub** [ControlPanel-gg/dashboard#691]
**Describe the bug 🐛**
Head on over to the partners tab in the admin area, go to select the user you want to become partnered with. Be greeted with a massive list of users because for some reason the developer thought it would be a good idea to use a drop down menu so the web server is forced to load every single user you have in the database within that drop down menu.

**To Reproduce**
1. Login to dashboard
2. Click on the partnered tab
3. Go to select the user you wish to be partnered with
4. Either the web page won't load or will lag like crazy until the web page has loaded every single user from the database.

**Expected behavior**
The drop down menu is good for dashboard users with a small amount of users and even with a couple 100 users you are going to have trouble finding the user you wish to partner with. The expected behaviour here is to have an text input box to put in the users EMAIL of which you wish to partner with so it applies directly to their account or perhaps their user ID.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version Latest

**Smartphone (please complete the following information):**
N/A

**Additional context**
This was all tested on running the latest stable build of pterodactyl, dashboard and php. Everything is latest and is not modified in anyway.

**Comment by 1day2die** [comment]
thanks. this is fixed in v0.9.1
