### ISSUE TITLE
[Bug] Git dependant installation

### ISSUE THREAD

**Issue by IceToast** [ControlPanel-gg/dashboard#692]
**Describe the bug 🐛**
Controlpanel requires to be installed with git -> AppServiceProvider relies on the git branch (at least accesses it)

**Expected behavior**
If the installation is not done with git -> ignore anything that has to do with git.

**Additional context**
`production.ERROR: ErrorException: file(/var/www/dashboard/.git/HEAD): Failed to open stream: No such file or directory in /var/www/dashboard/app/Providers/AppServiceProvider.php:119`

**Comment by 1day2die** [comment]
wait
it shouldnt

![image](https://user-images.githubusercontent.com/8725848/215797372-35a0edb2-6f4a-457a-87b7-14fb0d83866a.png)

**Comment by 1day2die** [comment]
https://github.com/ControlPanel-gg/dashboard/pull/693
