### ISSUE TITLE
Re-link Discord account

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#71]
Can you please add button to re-link your Discord account, it should be shown when you are verified in profile. 
Users can change username and avatar and it will be not auto updated. Or someone can also want to use their new Discord account and get verified role.

**Comment by anondev-sudo** [comment]
Don't make unlink button, make relink, so when you click on it you will be redirected to oauth url again to authorize and then given role on new account + on the old the role should be removed

**Comment by anondev-sudo** [comment]
Now users need to manually visit /auth/redirect url. Just add there button that will redirect you to that url when you have linked account and show text Re-link Discord account

**Comment by 1day2die** [comment]
Waiting for merge
