### ISSUE TITLE
Force Discord verification and show alert message

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#72]
Hi, can you please add config option FORCE_DISCORD_VERIFY in Configuration, if it's set to true, then when the user has verified email, another alert should be shown to verify also Discord account. And user should not be able to create servers and purchase credits when email and discord is not verified.

**Comment by snaildos** [comment]
100% yes.

**Comment by anondev-sudo** [comment]
Another idea: allow users to login using Discord, add Login using Discord button to login page

**Comment by anondev-sudo** [comment]
Maybe there should be that you can't login to the dashboard without verification of email and discord when this is enabled.
That when user register on dashboard, page will be displayed that you must verify your email by clicking on verification link (+ link to resend verification link)  and button to link discord account.

When user who has not verified email and discord logins to the dashboard, this page should be displayed too.

This will require email and discord verification before you can access dashboard. And maybe also without completing this, account on pterodactyl should not be created.

**Comment by anondev-sudo** [comment]
This was added
