### ISSUE TITLE
[Bug]: Store Page Name

### ISSUE THREAD

**Issue by GeckoBoy84** [ControlPanel-gg/dashboard#724]
### What is your request about?

Because controlpanel used to only be able to sell credits, the store header was the credit display name. However we now offer Server Slots which means it should be app name + store or similar.

### Branch

main

### Solution idea

"app name" + store or similar

### Additional Info

![image](https://user-images.githubusercontent.com/67899387/217064064-d986274a-4992-47f3-ad4c-bae3c88cfef3.png)

**Comment by LogischJo** [comment]
Looks reasonable. I will look into this tomorrow. What about making this App name + store or optionally something made up in the settings.

**Comment by GeckoBoy84** [comment]
My opinion would be app name + store

**Comment by IceToast** [comment]
Fixed in #736
