### ISSUE TITLE
Latest Pterodactyl dies

### ISSUE THREAD

**Issue by snaildos** [ControlPanel-gg/dashboard#73]
**Describe the bug 🐛**
When creating a user with both ControlPanel and Ptero on latest version, creating a user gets the created user instantly deleted

**To Reproduce**
1. Update everything
2. Create a account
3. Watch the account die
4. Check logs and it says its deleted

**Expected behavior**
dont die, and dont delete.

**Screenshots**
https://img.snaildos.com/u/62xCTP.png

Hope this get's fixed soon.

**Comment by AVMG20** [comment]
Does the user you're trying to create already exists on pterodactyl?

**Comment by anondev-sudo** [comment]
The activity logs should be more detailed as I have suggested.

**Comment by snaildos** [comment]
> Does the user you're trying to create already exists on pterodactyl? Because the only reason it would delete the user after creating it, is cuss pterodactyl trows an error ( meaning the user couldn't be created on pterodactyl panel )
> 

Ah yes. It is indeed. Thank you for the reply. Quick question before I close.. The verify discord button has disappeared?

**Comment by AVMG20** [comment]
> Ah yes. It is indeed. Thank you for the reply—quick question before I close. The verify discord button has disappeared?
If the button doesn't appear, you haven't set it up :) checkout your.env file and make sure to add the discord stuff. Afterwards, it will appear :)
