### ISSUE TITLE
[Bug]: Ticket system bug.

### ISSUE THREAD

**Issue by LevM-A** [ControlPanel-gg/dashboard#730]
### What is your request about?

![image](https://user-images.githubusercontent.com/59459622/217986866-66d66b68-9e77-411d-ac6c-77cc00e427e0.png)
The problem is that in Priority section there should be Low, or Medium, or High. 

### Branch

main

### Controlpanel Logs

I thing you don't need logs, because this problem is in codes

**Comment by 1day2die** [comment]
Haha thanks for this. We will Look into it and push a fix on the next Release

**Comment by LogischJo** [comment]
Im going to push a commit this afternoon in order to fix it.

**Comment by IceToast** [comment]
Fixed in #736
