### ISSUE TITLE
[Feature] Add the payment methods "SEPA", "MASTERCARD", ...

### ISSUE THREAD

**Issue by Shykuzo** [ControlPanel-gg/dashboard#733]
### Feature Description

Add the following payment methods:
  - SEPA
  - Mastercard / Maestro / ...
  - Bancontact (For Belgians)

### Solution Idea

Not everyone has a PayPal account and Stripe takes too much commission.
These payment methods are therefore more reliable, more convenient and more profitable than PayPal and Stripe.

**Comment by GeckoBoy84** [comment]
SEPA and Mastercard can be handled through stripe.

**Comment by Shykuzo** [comment]
> SEPA and Mastercard can be handled through stripe.

From what I can see, reading is not your strong point so I'll help you by cutting off my message:

`Not everyone has a PayPal account and Stripe takes too much commission.`

**Comment by GeckoBoy84** [comment]
No need to be rude.
I did read your message, however we will not be prioritising things that are already possible. Stripes fees are also one of the lowest out there…

**Comment by IceToast** [comment]
>Not everyone has a PayPal account and Stripe takes too much commission.

That's not true. Stripes cut is less than PayPals. 
We cannot support SEPA or Mastercard (or any other direkt transfer) as this will require licensing and following regulations. 
You will need to be a company that is registered and validated by those services to support that. This is exactly the reason why we choose payment services like PayPal and Stripe that do all of this for you by just taking a small cut.
