### ISSUE TITLE
[Bug]: Tickets when closed

### ISSUE THREAD

**Issue by GeckoBoy84** [ControlPanel-gg/dashboard#734]
### What is your request about?

When a ticket is closed on the dashboard, the close button is still visible on the ticket list
![image](https://user-images.githubusercontent.com/67899387/218150552-02b62ece-ae31-4516-beae-9a152ed77120.png)

### Branch

main

### Solution idea

The button should be replaced by a reopen button, this button should also be present on the ticket page.

**Comment by IceToast** [comment]
Fixed in #736
