### ISSUE TITLE
[Feature] Personalized Service

### ISSUE THREAD

**Issue by Shykuzo** [ControlPanel-gg/dashboard#737]
### Feature Description

1) Allow the user to create a personalized offer.

We should just define a price for each MB of Ram, for each % of CPU, for each GB of Storage, for each new port, ...

Once the user confirms his offer, it creates a server with the configuration he chose and displays the price.

2) Be able to give a server for free for a limited time with specific parameters.

From the Administrative panel, we select a user, we offer him a server that we can customize and with a limited free time.

### Solution Idea

It would be useful to allow customers to create an offer without going through a ticket but also very useful to be able to give servers for free for a limited time in order to facilitate giveaway for example.
for example.

**Comment by GeckoBoy84** [comment]
2 #130

**Comment by GeckoBoy84** [comment]
Please use separate issues for each request for this reason!
