### ISSUE TITLE
[Feature] More options for stopping abuse

### ISSUE THREAD

**Issue by OddPvP** [ControlPanel-gg/dashboard#748]
### Feature Description

More ways to stop abuse

### Solution Idea

Some ideas I have though of:
Add a way to block vpns via an API key to https://proxycheck.io/, https://ipinfo.io/ or some way to detect vpns/proxys
Add a way to not allow verifying discord accounts if its under an age set in settings

**Comment by IceToast** [comment]
This won't be implemented as it's way out of scope of this project.
If you need protection of any kind in this regard you should look into using firewalls or other software that may or may not interact with the webserver directly.
