### ISSUE TITLE
[Feature] version chhecker

### ISSUE THREAD

**Issue by sybetjeh** [ControlPanel-gg/dashboard#750]
### Feature Description

a version checker like in pterodactyl. it tells you if your instance is outdated & on what version you are on

### Solution Idea

implement a version checker somewhere on the overview page or sum

### Additional Info

no

**Comment by 1day2die** [comment]
This is imemented since v0.9.0 or 0.9.1 in admin overview

**Comment by sybetjeh** [comment]
girl no?

**Comment by sybetjeh** [comment]
![image](https://user-images.githubusercontent.com/54631194/220179867-419c84fd-c28e-4918-827e-7af8a134d200.png)
this yes but this doesn't tell you if you're outdated?

**Comment by sybetjeh** [comment]
it's useless

**Comment by GeckoBoy84** [comment]
Can confirm its implemented
![image](https://user-images.githubusercontent.com/67899387/220205160-b0db71db-fb6d-466c-bfd0-e8ada67a708d.png)
