### ISSUE TITLE
[Bug]: Deletable Admin Accounts

### ISSUE THREAD

**Issue by sourcevalue** [ControlPanel-gg/dashboard#762]
### What is your request about?

As the title implies, you can delete the administrator accounts. Which can brick your panel, and btw sorry for bricking your demo panel.

### Branch

main

**Comment by IceToast** [comment]
I agree that the last admin account should not be deletable. But it doesn't "brick" controlpanel if you do. You can create a admin account via CLI anytime you'd like. 

FYI: The demo panel resets every hour, no worries.
