### ISSUE TITLE
[Feature] Forced ssl/tls encrypten

### ISSUE THREAD

**Issue by IceToast** [ControlPanel-gg/dashboard#771]
### Feature Description

All routes returned by the route() helper function from laravel may return a unsecure url scheme (http::).
This can cause XMLHttpRequest errors that enforce the usage of the same scheme that the user is visiting the page from.

### Solution Idea

Forcing all requests (routes) using the https:: url scheme.
This can be done by using the URL::forceScheme()-method inside the AppServiceProvider boot() method or by grouping all routes in the routes/web.php file to use the https scheme.

### Additional Info

This also forces users to use the secure url scheme, which may or may not prevent user data to be leaked.

**Comment by AGuyNamedJens** [comment]
"Solution idea" forcing users is not entirely true, you can enforce it if people set a variable in the `.env` to true.  For example a snippet I use on my own project:
`if(\App::environment('APP_SSL')) {
     URL::forceScheme('https');
 }`

**Comment by IceToast** [comment]
You could also get the APP_URL variable and parse the URL scheme from it. If it is https -> enforce https scheme.
