### ISSUE TITLE
Set products per server location

### ISSUE THREAD

**Issue by Hiekki4** [ControlPanel-gg/dashboard#78]
Be able to choose which features can use a given location. 

For example I have 2 nodes ue1, ue2
And I want the started plan to only be able to use the ue1 location

**Comment by anondev-sudo** [comment]
Yeah, I have suggested to add product categories and that you can choose which eggs can be choosed for products in that product group.

**Comment by AVMG20** [comment]
can I change your title cuss it doesn't make any sense

**Comment by 1day2die** [comment]
This is currently in Dev Branch. Closing. Please feel free to re-open if im messing something up
