### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by igot2phones** [ControlPanel-gg/dashboard#782]
### Feature Description

Bonus credits at first time purchase.

### Solution Idea

the panel should have a one time credit bonus for new users that have never purchased credits before.

**Comment by IceToast** [comment]
Please follow the issue template and give it a well describing title.
A solution idea is not "The panel should do X or Y" but a brief idea on how this could be done. Not necessarily in a programmatic way but in a way that it can be used to implement such a feature. 

By not providing a description on how this system should work and interact with other parts of the software, it is necessary for a developer to think about it themself which may or may not result in a feature that fits your (and others) needs.
