### ISSUE TITLE
[feature] Install Script

### ISSUE THREAD

**Issue by mishal321** [ControlPanel-gg/dashboard#81]
# 🚀 Feature Request

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Add an install script, like the one that pterodactyl has, I think it would make it much easier for the people that do not know what they are doing.

**Comment by Ayaan-GuitarHost** [comment]
About install script it's not officiall and why install script if it's easy as hell to setup ?

**Comment by AVMG20** [comment]
JoJo already made efforts into an auto-update :)

**Comment by freddierick** [comment]
The problem with something like an install script is making it work in all use cases. If there is an error or a problem installing something the "people that do not know what they are doing" will have no idea what to do. It will just fill support channels with people who have never used Linux and should start with the very basics not installing this. 

The docker implementation is a much better option.

**Comment by LogischJo** [comment]
> The problem with something like an install script is making it work in all use cases. If there is an error or a problem installing something the "people that do not know what they are doing" will have no idea what to do. It will just fill support channels with people who have never used Linux and should start with the very basics not installing this.
> 
> The docker implementation is a much better option.

Exactly. Anyways, if anyone stuck installing they can just create a ticket in the Discord Channel

**Comment by 1day2die** [comment]
Closing this.
There now are multiple installation scripts and even Ptero eggs to install the dashboard (lol)

Feel free to re-open if im mistaken
