### ISSUE TITLE
[feature] 

### ISSUE THREAD

**Issue by SourCreamCulture** [ControlPanel-gg/dashboard#83]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

Yes, People can see how many credits or the exact specs of a plan before they purchase it.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

should have an option that shows all the info and perks, before buying, like maybe a info/packages section

### Additional context

*Is there anything else you can add about the proposal?
You might want to link to related issues here, if you haven't already.*

nope all the info is above

**Comment by AVMG20** [comment]
I have no clue what this is about
