### ISSUE TITLE
Remove CPU Restrictions

### ISSUE THREAD

**Issue by William071802** [ControlPanel-gg/dashboard#86]
# 🚀 Feature Request

I have noticed that when creating a "Product" in the Control Panel that we are forced to allocate at least 5% CPU to each server, however in the Pterodactyl Panel I can decrease this to, for example, 3% . While it may seem crazy to some, removing this arbitrary restriction could be very helpful. I'd like to offer free servers, and this would allow me more flexibility to do so without eating into resources as hard. Some CPUs are good enough that this could be viable for single server bots. (I am aware that this would increase boot times however it'd allow more free servers so I don't think people would mind, and if they do they're welcome to pay a small fee for more power)

**Comment by AVMG20** [comment]
I will change this back to 0 since in pterodactyl, giving 0 means unlimited. so changing this back to 0 would make this  this option available aswel :)

**Comment by AVMG20** [comment]
changed the required 5 to 0 
![image](https://user-images.githubusercontent.com/45005889/122988610-39093700-d3a2-11eb-9346-5f08153847fc.png)
