### ISSUE TITLE
Send email when server was (auto) suspended/deleted

### ISSUE THREAD

**Issue by anondev-sudo** [ControlPanel-gg/dashboard#91]
As payment notification was added, also notification when server has been auto-suspended (don't have credits) should be added.

And also when admins manually delete or suspend server, email should be sent to user, and there should be that Hello {user}, your server has been deleted/suspended, please ask {app name} staff team for more details.
Server details:
Name: {server name}

I have opened issue on pterodactyl to send email when server was suspended, but they told that email notification when server is deleted or suspended should be sent from billing software.

**Comment by AVMG20** [comment]
You know, a person can have many servers, and they basically all suspend all at once; if a person would, for example, have 8 servers, he would be notified 8 ways doing it this way. I wanted to make it so that he gets a notification whenever;

-  (all) his servers are suspended

-  some 1 manually suspends his server

- x days before his servers are about to be suspended

**Comment by AVMG20** [comment]
please use the template we provide :)

**Comment by anondev-sudo** [comment]
> You know, a person can have many servers, and they basically all suspend all at once; if a person would, for example, have 8 servers, he would be notified 8 ways doing it this way. I wanted to make it so that he gets a notification whenever;
> 
> * (all) his servers are suspended
> * some 1 manually suspends his server
> * x days before his servers are about to be suspended


Yeah, this is good to alert the user in one email and more servers were suspended, and the notification to purchase credits should be sent 5 days before the server(s) will be auto suspended

**Comment by anondev-sudo** [comment]
Partially added, but when admin deletes or suspends server, email notification should be sent too.

**Comment by 1day2die** [comment]
This is a thing already?
Re-Open if im wrong
