### ISSUE TITLE
Ads System on panel (I can pay for this) 

### ISSUE THREAD

**Issue by TangoBeee** [ControlPanel-gg/dashboard#92]
# 🚀 Feature Request (Ads System on Panel) 

### Need a ads system in controlpanel.gg means there should be ads by which we can earn if we are giving the service for free and I can give 10 to 15€ for this feature.
I can pay more if needed
Discord user name : TangoBee#2842

**Comment by AVMG20** [comment]
We will not be supporting this feature; you could make something yourself since the code is open-source :) or use our API to make something like this externally.
