### ISSUE TITLE
[feature] Manual Verification

### ISSUE THREAD

**Issue by GeckoBoy84** [ControlPanel-gg/dashboard#99]
# 🚀 Feature Request

### Is your proposal related to a problem?

*Provide a clear and concise description of what the problem is.
For example, "I can't change x and it makes me have to do manual work"*

When you are testing, you may not have an SMTP server (Or it may not work) so you are unable to verify your account.

### Describe the solution you'd like

*Provide a clear and concise description of what you want to happen.
For Example, "Automate the changing of x so I don't have to do it manually"*

Add a manual verification button to admin panel user tab and also a way to do it through console.

**Comment by AVMG20** [comment]
Email verification is not required to use this dashboard; email verification does nothing besides confirming the email is confirmed, and it's safe to assume emails can be sent towards this email address. If your mail server is not working, there is literally no point in forcing this value to be true.
